<!-- Cashup summary modal -->
<div class="modal printable" id="cashupSummaryModal" tabindex="-1" role="dialog" aria-labelledby="cashupSummaryLabel">
 <div class="modal-dialog modal-lg">
 <div class="modal-content">
 <div class="modal-header">
 <h1 class="modal-title" id="cashupSummaryLabel">Tilitysten yhteenveto</h1>
 <button aria-label="Sulje" class="btn-close" data-bs-dismiss="modal" type="button"></button>
 </div>
 <div class="modal-body">
 <ul>
 <li>Kassa: <span id="register_description"></span></li>
 <li>Jakso: <span id="from_date"></span> - <span id="to_date"></span></li>
 </ul>
 <table>
 <thead>
 <tr>
 <th>Tyyppi</th>
 <th>Yhteensä</th>
 </tr>
 </thead>
 <tbody>
 </tbody>
 <tfoot>
 </tfoot>
 </table>
 </div> <!-- /.modal-body -->
 <div class="modal-footer">
 <button type="button" class="printModal btn btn-primary"><i class="fa fa-print"></i> Tulosta</button>
 <button type="button" class="btn btn-default" data-bs-dismiss="modal">Sulje</button>
 </div> <!-- /.modal-footer -->
 </div> <!-- /.modal-content -->
 </div> <!-- /.modal-dialog -->
</div> <!-- /#cashupSummaryModal -->
