<!-- Checkout renewals modal -->
<div id="checkoutRenewals" class="modal" tabindex="-1" role="dialog" aria-labelledby="checkoutRenewalsLabel" aria-hidden="true">
 <div class="modal-dialog">
 <div class="modal-content">
 <div class="modal-header">
 <h1 class="modal-title" id="checkoutRenewalsLabel"> Niteiden uusinnat</h1>
 <button aria-label="Sulje" class="btn-close" data-bs-dismiss="modal" type="button"></button>
 </div> <!-- /.modal-header -->
 <div class="modal-body">
 <div id="retrieving" class="alert" style="display:none">Haetaan uusintoja...</div>
 <div id="incomplete" class="alert" style="display:none"></div>
 <ul id="results" style="display:none"></ul>
 </div> <!-- /.modal-body -->
 <div class="modal-footer">
 <button class="btn btn-default" data-bs-dismiss="modal">Sulje</button>
 </div> <!-- /.modal-footer -->
 </div> <!-- /.modal-content -->
 </div> <!-- /.modal-dialog -->
</div> <!-- /#checkoutRenewals -->
