---
/config/file_transports:
  get:
    x-mojo-to: Config::File::Transports#list
    operationId: listFileTransportServers
    tags:
      - file_transports
    summary: List File transports
    produces:
      - application/json
    parameters:
      - $ref: "../swagger.yaml#/parameters/match"
      - $ref: "../swagger.yaml#/parameters/order_by"
      - $ref: "../swagger.yaml#/parameters/page"
      - $ref: "../swagger.yaml#/parameters/per_page"
      - $ref: "../swagger.yaml#/parameters/q_param"
      - $ref: "../swagger.yaml#/parameters/q_body"
      - $ref: "../swagger.yaml#/parameters/request_id_header"
    responses:
      "200":
        description: A list of File transports
        schema:
          type: array
          items:
            $ref: "../swagger.yaml#/definitions/file_transport"
      "400":
        description: |
          Bad request. Possible `error_code` attribute values:

            * `invalid_query`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "403":
        description: Access forbidden
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "500":
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "503":
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        parameters: manage_file_transports
  post:
    x-mojo-to: Config::File::Transports#add
    operationId: addFileTransportServer
    tags:
      - file_transports
    summary: Add File transport
    parameters:
      - name: body
        in: body
        description: A JSON object representing a new File transport configuration
        required: true
        schema:
          $ref: "../swagger.yaml#/definitions/file_transport"
    produces:
      - application/json
    responses:
      "201":
        description: An File transport object
        schema:
          $ref: "../swagger.yaml#/definitions/file_transport"
      "400":
        description: Bad request
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "401":
        description: Authentication required
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "403":
        description: Access forbidden
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "409":
        description: Conflict in creating resource
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "500":
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "503":
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        parameters: manage_file_transports
"/config/file_transports/{file_transport_id}":
  get:
    x-mojo-to: Config::File::Transports#get
    operationId: getFileTransportServer
    tags:
      - file_transports
    summary: Get File transport
    parameters:
      - $ref: "../swagger.yaml#/parameters/file_transport_id_pp"
    produces:
      - application/json
    responses:
      "200":
        description: An File transport object
        schema:
          $ref: "../swagger.yaml#/definitions/file_transport"
      "400":
        description: Bad request
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "404":
        description: Object not found
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "409":
        description: Conflict updating resource
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "500":
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "503":
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        parameters: manage_file_transports
  put:
    x-mojo-to: Config::File::Transports#update
    operationId: updateFileTransportServer
    tags:
      - file_transports
    summary: Update File transport
    parameters:
      - $ref: "../swagger.yaml#/parameters/file_transport_id_pp"
      - name: body
        in: body
        description: An File transport object
        required: true
        schema:
          $ref: "../swagger.yaml#/definitions/file_transport"
    produces:
      - application/json
    responses:
      "200":
        description: An File transport object
        schema:
          $ref: "../swagger.yaml#/definitions/file_transport"
      "400":
        description: Bad request
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "401":
        description: Authentication required
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "403":
        description: Access forbidden
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "404":
        description: Object not found
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "500":
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "503":
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        parameters: manage_file_transports
  delete:
    x-mojo-to: Config::File::Transports#delete
    operationId: deleteFileTransportServer
    tags:
      - file_transports
    summary: Delete File transport
    parameters:
      - $ref: "../swagger.yaml#/parameters/file_transport_id_pp"
    produces:
      - application/json
    responses:
      "204":
        description: File transport deleted
      "400":
        description: Bad request
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "401":
        description: Authentication required
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "403":
        description: Access forbidden
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "404":
        description: Object not found
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "500":
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "503":
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        parameters: manage_file_transports
