<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stylesheet>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<!-- This file generated by generate_MARC21Languages.pl -->
 <xsl:template name="languageCodeText">
 <xsl:param name="code"/>
 <xsl:choose>
 <xsl:when test="$code='abk'"><xsl:text>Abkhaziska</xsl:text></xsl:when>
 <xsl:when test="$code='ace'"><xsl:text>Acehnesiska</xsl:text></xsl:when>
 <xsl:when test="$code='ach'"><xsl:text>Acoli</xsl:text></xsl:when>
 <xsl:when test="$code='ada'"><xsl:text>Adangme</xsl:text></xsl:when>
 <xsl:when test="$code='ady'"><xsl:text>Adygeiska</xsl:text></xsl:when>
 <xsl:when test="$code='aar'"><xsl:text>Afar</xsl:text></xsl:when>
 <xsl:when test="$code='afh'"><xsl:text>Afrihili (Konstgjort språk)</xsl:text></xsl:when>
 <xsl:when test="$code='afr'"><xsl:text>Afrikaans</xsl:text></xsl:when>
 <xsl:when test="$code='afa'"><xsl:text>Afroasiatiska (Övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='ain'"><xsl:text>Ainu</xsl:text></xsl:when>
 <xsl:when test="$code='aka'"><xsl:text>Akan</xsl:text></xsl:when>
 <xsl:when test="$code='akk'"><xsl:text>Akkadiska</xsl:text></xsl:when>
 <xsl:when test="$code='alb'"><xsl:text>Albanska</xsl:text></xsl:when>
 <xsl:when test="$code='ale'"><xsl:text>Aleutiska</xsl:text></xsl:when>
 <xsl:when test="$code='alg'"><xsl:text>Algonkinska (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='alt'"><xsl:text>Altaiska</xsl:text></xsl:when>
 <xsl:when test="$code='tut'"><xsl:text>Altaiska (Övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='amh'"><xsl:text>Amhariska</xsl:text></xsl:when>
 <xsl:when test="$code='anp'"><xsl:text>Angika</xsl:text></xsl:when>
 <xsl:when test="$code='apa'"><xsl:text>Apachiskt språk</xsl:text></xsl:when>
 <xsl:when test="$code='ara'"><xsl:text>Arabiska</xsl:text></xsl:when>
 <xsl:when test="$code='arg'"><xsl:text>Aragonsk spanska</xsl:text></xsl:when>
 <xsl:when test="$code='arc'"><xsl:text>Arameiska</xsl:text></xsl:when>
 <xsl:when test="$code='arp'"><xsl:text>Arapaho</xsl:text></xsl:when>
 <xsl:when test="$code='arw'"><xsl:text>Arawakiska</xsl:text></xsl:when>
 <xsl:when test="$code='arm'"><xsl:text>Armeniska</xsl:text></xsl:when>
 <xsl:when test="$code='rup'"><xsl:text>Arumänska</xsl:text></xsl:when>
 <xsl:when test="$code='art'"><xsl:text>Konstgjorda språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='asm'"><xsl:text>Assamesiska</xsl:text></xsl:when>
 <xsl:when test="$code='ath'"><xsl:text>Athabaskiska (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='aus'"><xsl:text>Australiskt språk</xsl:text></xsl:when>
 <xsl:when test="$code='map'"><xsl:text>Austronesiska (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='ava'"><xsl:text>Avariskt språk</xsl:text></xsl:when>
 <xsl:when test="$code='ave'"><xsl:text>Avestiska</xsl:text></xsl:when>
 <xsl:when test="$code='awa'"><xsl:text>Awadhi</xsl:text></xsl:when>
 <xsl:when test="$code='aym'"><xsl:text>Aymara</xsl:text></xsl:when>
 <xsl:when test="$code='aze'"><xsl:text>Azerbajdzjanska</xsl:text></xsl:when>
 <xsl:when test="$code='ast'"><xsl:text>Asturiska (Bable)</xsl:text></xsl:when>
 <xsl:when test="$code='ban'"><xsl:text>Balinesiska</xsl:text></xsl:when>
 <xsl:when test="$code='bat'"><xsl:text>Baltiska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='bal'"><xsl:text>Baluchi</xsl:text></xsl:when>
 <xsl:when test="$code='bam'"><xsl:text>Bambara</xsl:text></xsl:when>
 <xsl:when test="$code='bai'"><xsl:text>Bamilekespråk</xsl:text></xsl:when>
 <xsl:when test="$code='bad'"><xsl:text>Bandaspråk</xsl:text></xsl:when>
 <xsl:when test="$code='bnt'"><xsl:text>Bantuspråk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='bas'"><xsl:text>Basa (Bantuspråk)</xsl:text></xsl:when>
 <xsl:when test="$code='bak'"><xsl:text>Basjkiriska</xsl:text></xsl:when>
 <xsl:when test="$code='baq'"><xsl:text>Baskiska</xsl:text></xsl:when>
 <xsl:when test="$code='btk'"><xsl:text>Batak</xsl:text></xsl:when>
 <xsl:when test="$code='bej'"><xsl:text>Beyja</xsl:text></xsl:when>
 <xsl:when test="$code='bel'"><xsl:text>Belarusiska</xsl:text></xsl:when>
 <xsl:when test="$code='bem'"><xsl:text>Bemba</xsl:text></xsl:when>
 <xsl:when test="$code='ben'"><xsl:text>Bengali</xsl:text></xsl:when>
 <xsl:when test="$code='ber'"><xsl:text>Berberspråk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='bho'"><xsl:text>Bhojpuri</xsl:text></xsl:when>
 <xsl:when test="$code='bih'"><xsl:text>Bihari (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='bik'"><xsl:text>Bikol</xsl:text></xsl:when>
 <xsl:when test="$code='byn'"><xsl:text>Bilin</xsl:text></xsl:when>
 <xsl:when test="$code='bis'"><xsl:text>Bislama</xsl:text></xsl:when>
 <xsl:when test="$code='zbl'"><xsl:text>Bliss</xsl:text></xsl:when>
 <xsl:when test="$code='bos'"><xsl:text>Bosniska</xsl:text></xsl:when>
 <xsl:when test="$code='bra'"><xsl:text>Braj</xsl:text></xsl:when>
 <xsl:when test="$code='bre'"><xsl:text>Bretonska</xsl:text></xsl:when>
 <xsl:when test="$code='bug'"><xsl:text>Buginesiska</xsl:text></xsl:when>
 <xsl:when test="$code='bul'"><xsl:text>Bulgariska</xsl:text></xsl:when>
 <xsl:when test="$code='bua'"><xsl:text>Burjatiska</xsl:text></xsl:when>
 <xsl:when test="$code='bur'"><xsl:text>Burmesiska</xsl:text></xsl:when>
 <xsl:when test="$code='cad'"><xsl:text>Caddo</xsl:text></xsl:when>
 <xsl:when test="$code='car'"><xsl:text>Karibiska</xsl:text></xsl:when>
 <xsl:when test="$code='cat'"><xsl:text>Katalanska</xsl:text></xsl:when>
 <xsl:when test="$code='cau'"><xsl:text>Kaukasiska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='ceb'"><xsl:text>Cebuano</xsl:text></xsl:when>
 <xsl:when test="$code='cel'"><xsl:text>Keltiska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='cai'"><xsl:text>Centralamerikanskt indianspråk</xsl:text></xsl:when>
 <xsl:when test="$code='chg'"><xsl:text>Chagatai</xsl:text></xsl:when>
 <xsl:when test="$code='cmc'"><xsl:text>Chamic</xsl:text></xsl:when>
 <xsl:when test="$code='cha'"><xsl:text>Chamorro</xsl:text></xsl:when>
 <xsl:when test="$code='che'"><xsl:text>Tjetjenska</xsl:text></xsl:when>
 <xsl:when test="$code='chr'"><xsl:text>Cherokesiska</xsl:text></xsl:when>
 <xsl:when test="$code='chy'"><xsl:text>Cheyenne</xsl:text></xsl:when>
 <xsl:when test="$code='chb'"><xsl:text>Chibcha</xsl:text></xsl:when>
 <xsl:when test="$code='chi'"><xsl:text>Kinesiska</xsl:text></xsl:when>
 <xsl:when test="$code='chn'"><xsl:text>Chinook</xsl:text></xsl:when>
 <xsl:when test="$code='chp'"><xsl:text>Chopi</xsl:text></xsl:when>
 <xsl:when test="$code='cho'"><xsl:text>Choctaw</xsl:text></xsl:when>
 <xsl:when test="$code='chu'"><xsl:text>Fornkyrkslaviska</xsl:text></xsl:when>
 <xsl:when test="$code='chk'"><xsl:text>Chuukesiska; Truk</xsl:text></xsl:when>
 <xsl:when test="$code='chv'"><xsl:text>Tjuvasjiska</xsl:text></xsl:when>
 <xsl:when test="$code='cop'"><xsl:text>Koptiska</xsl:text></xsl:when>
 <xsl:when test="$code='cor'"><xsl:text>Korniska</xsl:text></xsl:when>
 <xsl:when test="$code='cos'"><xsl:text>Korsikanska</xsl:text></xsl:when>
 <xsl:when test="$code='cre'"><xsl:text>Cree</xsl:text></xsl:when>
 <xsl:when test="$code='mus'"><xsl:text>Muskogée</xsl:text></xsl:when>
 <xsl:when test="$code='crp'"><xsl:text>Kreol- och pidginspråk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='cpe'"><xsl:text>Kreol- och pidginspråk, engelskbaserade (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='cpf'"><xsl:text>Kreol- och pidginspråk, franskbaserade (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='cpp'"><xsl:text>Kreol- och pidginspråk, portugisiskbaserade (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='crh'"><xsl:text>Krimtatariska</xsl:text></xsl:when>
 <xsl:when test="$code='hrv'"><xsl:text>Kroatiska</xsl:text></xsl:when>
 <xsl:when test="$code='cus'"><xsl:text>Kusjitiska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='cze'"><xsl:text>Tjeckiska</xsl:text></xsl:when>
 <xsl:when test="$code='dak'"><xsl:text>Dakota</xsl:text></xsl:when>
 <xsl:when test="$code='dan'"><xsl:text>Danska</xsl:text></xsl:when>
 <xsl:when test="$code='dar'"><xsl:text>Darginska</xsl:text></xsl:when>
 <xsl:when test="$code='day'"><xsl:text>Dayak</xsl:text></xsl:when>
 <xsl:when test="$code='del'"><xsl:text>Delaware</xsl:text></xsl:when>
 <xsl:when test="$code='din'"><xsl:text>Dinka</xsl:text></xsl:when>
 <xsl:when test="$code='div'"><xsl:text>Divehi</xsl:text></xsl:when>
 <xsl:when test="$code='doi'"><xsl:text>Dogri</xsl:text></xsl:when>
 <xsl:when test="$code='dgr'"><xsl:text>Dogrib</xsl:text></xsl:when>
 <xsl:when test="$code='dra'"><xsl:text>Dravidiska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='dua'"><xsl:text>Duala</xsl:text></xsl:when>
 <xsl:when test="$code='dut'"><xsl:text>Nederländska</xsl:text></xsl:when>
 <xsl:when test="$code='dum'"><xsl:text>Medelnederländska (ca. 1050-1350)</xsl:text></xsl:when>
 <xsl:when test="$code='dyu'"><xsl:text>Dioula</xsl:text></xsl:when>
 <xsl:when test="$code='dzo'"><xsl:text>Dzongkha</xsl:text></xsl:when>
 <xsl:when test="$code='frs'"><xsl:text>Östfrisiska</xsl:text></xsl:when>
 <xsl:when test="$code='bin'"><xsl:text>Edo</xsl:text></xsl:when>
 <xsl:when test="$code='efi'"><xsl:text>Efik</xsl:text></xsl:when>
 <xsl:when test="$code='egy'"><xsl:text>Egyptiska</xsl:text></xsl:when>
 <xsl:when test="$code='eka'"><xsl:text>Ekajuk</xsl:text></xsl:when>
 <xsl:when test="$code='elx'"><xsl:text>Elamitiska</xsl:text></xsl:when>
 <xsl:when test="$code='eng'"><xsl:text>Engelska</xsl:text></xsl:when>
 <xsl:when test="$code='enm'"><xsl:text>Engelska, medel- (1100-1500)</xsl:text></xsl:when>
 <xsl:when test="$code='ang'"><xsl:text>Fornengelska (ca. 450-1100)</xsl:text></xsl:when>
 <xsl:when test="$code='myv'"><xsl:text>Erzya</xsl:text></xsl:when>
 <xsl:when test="$code='epo'"><xsl:text>Esperanto</xsl:text></xsl:when>
 <xsl:when test="$code='est'"><xsl:text>Estniska</xsl:text></xsl:when>
 <xsl:when test="$code='gez'"><xsl:text>Etiopiska språk</xsl:text></xsl:when>
 <xsl:when test="$code='ewe'"><xsl:text>Ewe</xsl:text></xsl:when>
 <xsl:when test="$code='ewo'"><xsl:text>Ewondo</xsl:text></xsl:when>
 <xsl:when test="$code='fan'"><xsl:text>Fang</xsl:text></xsl:when>
 <xsl:when test="$code='fat'"><xsl:text>Fanti</xsl:text></xsl:when>
 <xsl:when test="$code='fao'"><xsl:text>Färöiska</xsl:text></xsl:when>
 <xsl:when test="$code='fij'"><xsl:text>Fidjianska</xsl:text></xsl:when>
 <xsl:when test="$code='fil'"><xsl:text>Filippinska</xsl:text></xsl:when>
 <xsl:when test="$code='fin'"><xsl:text>Finska</xsl:text></xsl:when>
 <xsl:when test="$code='fiu'"><xsl:text>Finsk-ugriska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='fon'"><xsl:text>Fon</xsl:text></xsl:when>
 <xsl:when test="$code='fre'"><xsl:text>Franska</xsl:text></xsl:when>
 <xsl:when test="$code='frm'"><xsl:text>Medelfranska (ca. 1300-1600)</xsl:text></xsl:when>
 <xsl:when test="$code='fro'"><xsl:text>Fornfranska (ca. 842-1300)</xsl:text></xsl:when>
 <xsl:when test="$code='fry'"><xsl:text>Frisiska</xsl:text></xsl:when>
 <xsl:when test="$code='fur'"><xsl:text>Friuliska</xsl:text></xsl:when>
 <xsl:when test="$code='ful'"><xsl:text>Fula</xsl:text></xsl:when>
 <xsl:when test="$code='gaa'"><xsl:text>Ga</xsl:text></xsl:when>
 <xsl:when test="$code='glg'"><xsl:text>Galiciska</xsl:text></xsl:when>
 <xsl:when test="$code='lug'"><xsl:text>Luganda</xsl:text></xsl:when>
 <xsl:when test="$code='gay'"><xsl:text>Gayo</xsl:text></xsl:when>
 <xsl:when test="$code='gba'"><xsl:text>Gbaya</xsl:text></xsl:when>
 <xsl:when test="$code='geo'"><xsl:text>Georgiska</xsl:text></xsl:when>
 <xsl:when test="$code='ger'"><xsl:text>Tyska</xsl:text></xsl:when>
 <xsl:when test="$code='gmh'"><xsl:text>Medelhögtyska (ca. 1050-1500)</xsl:text></xsl:when>
 <xsl:when test="$code='goh'"><xsl:text>Fornhögtyska (ca. 750-1050)</xsl:text></xsl:when>
 <xsl:when test="$code='gem'"><xsl:text>Germanska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='gil'"><xsl:text>Kiribatiska</xsl:text></xsl:when>
 <xsl:when test="$code='gon'"><xsl:text>Gond</xsl:text></xsl:when>
 <xsl:when test="$code='gor'"><xsl:text>Gorontalo</xsl:text></xsl:when>
 <xsl:when test="$code='got'"><xsl:text>Gotiska</xsl:text></xsl:when>
 <xsl:when test="$code='grb'"><xsl:text>Grebo</xsl:text></xsl:when>
 <xsl:when test="$code='grc'"><xsl:text>Klassisk grekiska (till 1453)</xsl:text></xsl:when>
 <xsl:when test="$code='gre'"><xsl:text>Nygrekiska (1453- )</xsl:text></xsl:when>
 <xsl:when test="$code='grn'"><xsl:text>Guarani</xsl:text></xsl:when>
 <xsl:when test="$code='guj'"><xsl:text>Gujarati</xsl:text></xsl:when>
 <xsl:when test="$code='gwi'"><xsl:text>Gwich'in</xsl:text></xsl:when>
 <xsl:when test="$code='hai'"><xsl:text>Haida</xsl:text></xsl:when>
 <xsl:when test="$code='hat'"><xsl:text>Haitisk kreol</xsl:text></xsl:when>
 <xsl:when test="$code='hau'"><xsl:text>Hausa</xsl:text></xsl:when>
 <xsl:when test="$code='haw'"><xsl:text>Hawaiiska</xsl:text></xsl:when>
 <xsl:when test="$code='heb'"><xsl:text>Hebreiska</xsl:text></xsl:when>
 <xsl:when test="$code='her'"><xsl:text>Herero</xsl:text></xsl:when>
 <xsl:when test="$code='hil'"><xsl:text>Hiligaynon</xsl:text></xsl:when>
 <xsl:when test="$code='hin'"><xsl:text>Hindi</xsl:text></xsl:when>
 <xsl:when test="$code='hmo'"><xsl:text>Hiri Motu</xsl:text></xsl:when>
 <xsl:when test="$code='hit'"><xsl:text>Hettitiska</xsl:text></xsl:when>
 <xsl:when test="$code='hmn'"><xsl:text>Hmongspråk</xsl:text></xsl:when>
 <xsl:when test="$code='hun'"><xsl:text>Ungerska</xsl:text></xsl:when>
 <xsl:when test="$code='hup'"><xsl:text>Hupa</xsl:text></xsl:when>
 <xsl:when test="$code='iba'"><xsl:text>Iban</xsl:text></xsl:when>
 <xsl:when test="$code='ice'"><xsl:text>Isländska</xsl:text></xsl:when>
 <xsl:when test="$code='ido'"><xsl:text>Ido</xsl:text></xsl:when>
 <xsl:when test="$code='ibo'"><xsl:text>Igbo</xsl:text></xsl:when>
 <xsl:when test="$code='ijo'"><xsl:text>Ijo</xsl:text></xsl:when>
 <xsl:when test="$code='ilo'"><xsl:text>Ilokano</xsl:text></xsl:when>
 <xsl:when test="$code='smn'"><xsl:text>Enaresamiska</xsl:text></xsl:when>
 <xsl:when test="$code='inc'"><xsl:text>Indo-ariska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='ine'"><xsl:text>Indoeuropeiska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='ind'"><xsl:text>Indonesiska</xsl:text></xsl:when>
 <xsl:when test="$code='inh'"><xsl:text>Ingusjiska</xsl:text></xsl:when>
 <xsl:when test="$code='ina'"><xsl:text>Interlingua</xsl:text></xsl:when>
 <xsl:when test="$code='ile'"><xsl:text>Interlingue</xsl:text></xsl:when>
 <xsl:when test="$code='iku'"><xsl:text>Inuktitut</xsl:text></xsl:when>
 <xsl:when test="$code='ipk'"><xsl:text>Iñupiaq</xsl:text></xsl:when>
 <xsl:when test="$code='ira'"><xsl:text>Iranska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='gle'"><xsl:text>Iriska</xsl:text></xsl:when>
 <xsl:when test="$code='mga'"><xsl:text>Medeliriska (ca. 1100-1500)</xsl:text></xsl:when>
 <xsl:when test="$code='sga'"><xsl:text>Forniriska (till 1100)</xsl:text></xsl:when>
 <xsl:when test="$code='iro'"><xsl:text>Irokesiska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='ita'"><xsl:text>Italienska</xsl:text></xsl:when>
 <xsl:when test="$code='jpn'"><xsl:text>Japanska</xsl:text></xsl:when>
 <xsl:when test="$code='jav'"><xsl:text>Javanesiska</xsl:text></xsl:when>
 <xsl:when test="$code='jrb'"><xsl:text>Judeo-arabiska</xsl:text></xsl:when>
 <xsl:when test="$code='jpr'"><xsl:text>Judepersiska</xsl:text></xsl:when>
 <xsl:when test="$code='kbd'"><xsl:text>Kabardinska</xsl:text></xsl:when>
 <xsl:when test="$code='kab'"><xsl:text>Kabyliska</xsl:text></xsl:when>
 <xsl:when test="$code='kac'"><xsl:text>Kachin</xsl:text></xsl:when>
 <xsl:when test="$code='kal'"><xsl:text>Kalâtdlisut</xsl:text></xsl:when>
 <xsl:when test="$code='kam'"><xsl:text>Kamba</xsl:text></xsl:when>
 <xsl:when test="$code='kan'"><xsl:text>Kanaresiska</xsl:text></xsl:when>
 <xsl:when test="$code='kau'"><xsl:text>Kanuri</xsl:text></xsl:when>
 <xsl:when test="$code='krc'"><xsl:text>Karatjajbalkariska</xsl:text></xsl:when>
 <xsl:when test="$code='kaa'"><xsl:text>Karakalpakiska</xsl:text></xsl:when>
 <xsl:when test="$code='krl'"><xsl:text>Karelska</xsl:text></xsl:when>
 <xsl:when test="$code='kar'"><xsl:text>Karenspråk</xsl:text></xsl:when>
 <xsl:when test="$code='kas'"><xsl:text>Kashmiri</xsl:text></xsl:when>
 <xsl:when test="$code='csb'"><xsl:text>Kasjubiska</xsl:text></xsl:when>
 <xsl:when test="$code='kaw'"><xsl:text>Fornjavanska</xsl:text></xsl:when>
 <xsl:when test="$code='kaz'"><xsl:text>Kazakiska</xsl:text></xsl:when>
 <xsl:when test="$code='kha'"><xsl:text>Khasi</xsl:text></xsl:when>
 <xsl:when test="$code='khm'"><xsl:text>Kambodjanska</xsl:text></xsl:when>
 <xsl:when test="$code='khi'"><xsl:text>Khoisanspråk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='kho'"><xsl:text>Sakiska</xsl:text></xsl:when>
 <xsl:when test="$code='kik'"><xsl:text>Kikuyu</xsl:text></xsl:when>
 <xsl:when test="$code='kmb'"><xsl:text>Mbundu; Kimbundu</xsl:text></xsl:when>
 <xsl:when test="$code='kin'"><xsl:text>Rwanda</xsl:text></xsl:when>
 <xsl:when test="$code='tlh'"><xsl:text>Klingonska (konstgjort språk)</xsl:text></xsl:when>
 <xsl:when test="$code='kom'"><xsl:text>Komi</xsl:text></xsl:when>
 <xsl:when test="$code='kon'"><xsl:text>Kikongo</xsl:text></xsl:when>
 <xsl:when test="$code='kok'"><xsl:text>Konkani</xsl:text></xsl:when>
 <xsl:when test="$code='kut'"><xsl:text>Kutenai</xsl:text></xsl:when>
 <xsl:when test="$code='kor'"><xsl:text>Koreanska</xsl:text></xsl:when>
 <xsl:when test="$code='kos'"><xsl:text>Koreanska</xsl:text></xsl:when>
 <xsl:when test="$code='kpe'"><xsl:text>Kpelle</xsl:text></xsl:when>
 <xsl:when test="$code='kro'"><xsl:text>Kruspråk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='kua'"><xsl:text>Oshiwambo</xsl:text></xsl:when>
 <xsl:when test="$code='kum'"><xsl:text>Kumyk</xsl:text></xsl:when>
 <xsl:when test="$code='kur'"><xsl:text>Kurdiska</xsl:text></xsl:when>
 <xsl:when test="$code='kru'"><xsl:text>Indisk kurux</xsl:text></xsl:when>
 <xsl:when test="$code='kir'"><xsl:text>Kirgiziska</xsl:text></xsl:when>
 <xsl:when test="$code='lad'"><xsl:text>Ladino</xsl:text></xsl:when>
 <xsl:when test="$code='lah'"><xsl:text>Lahnda</xsl:text></xsl:when>
 <xsl:when test="$code='lam'"><xsl:text>Lamba</xsl:text></xsl:when>
 <xsl:when test="$code='lao'"><xsl:text>Laotiska</xsl:text></xsl:when>
 <xsl:when test="$code='lat'"><xsl:text>Latin</xsl:text></xsl:when>
 <xsl:when test="$code='lav'"><xsl:text>lettiska</xsl:text></xsl:when>
 <xsl:when test="$code='lez'"><xsl:text>Lesgiska</xsl:text></xsl:when>
 <xsl:when test="$code='lim'"><xsl:text>Limburgiska</xsl:text></xsl:when>
 <xsl:when test="$code='lin'"><xsl:text>Lingala</xsl:text></xsl:when>
 <xsl:when test="$code='lit'"><xsl:text>Litauiska</xsl:text></xsl:when>
 <xsl:when test="$code='jbo'"><xsl:text>Lojban (konstgjort språk)</xsl:text></xsl:when>
 <xsl:when test="$code='nds'"><xsl:text>Lågtyska</xsl:text></xsl:when>
 <xsl:when test="$code='dsb'"><xsl:text>Lågsorbiska</xsl:text></xsl:when>
 <xsl:when test="$code='loz'"><xsl:text>Lozi</xsl:text></xsl:when>
 <xsl:when test="$code='lub'"><xsl:text>Luba-Katanga</xsl:text></xsl:when>
 <xsl:when test="$code='lua'"><xsl:text>Luba-Lulua</xsl:text></xsl:when>
 <xsl:when test="$code='lui'"><xsl:text>Luiseño</xsl:text></xsl:when>
 <xsl:when test="$code='smj'"><xsl:text>Lulesamiska</xsl:text></xsl:when>
 <xsl:when test="$code='lun'"><xsl:text>Lunda</xsl:text></xsl:when>
 <xsl:when test="$code='luo'"><xsl:text>Luo (Kenya och Tanzania)</xsl:text></xsl:when>
 <xsl:when test="$code='lus'"><xsl:text>Mizo</xsl:text></xsl:when>
 <xsl:when test="$code='ltz'"><xsl:text>Luxemburgiska</xsl:text></xsl:when>
 <xsl:when test="$code='mac'"><xsl:text>Makedonska</xsl:text></xsl:when>
 <xsl:when test="$code='mad'"><xsl:text>Maduresiska</xsl:text></xsl:when>
 <xsl:when test="$code='mag'"><xsl:text>Magahi</xsl:text></xsl:when>
 <xsl:when test="$code='mai'"><xsl:text>Maithili</xsl:text></xsl:when>
 <xsl:when test="$code='mak'"><xsl:text>Makasar</xsl:text></xsl:when>
 <xsl:when test="$code='mlg'"><xsl:text>Malagassiska</xsl:text></xsl:when>
 <xsl:when test="$code='may'"><xsl:text>Malajiska</xsl:text></xsl:when>
 <xsl:when test="$code='mal'"><xsl:text>Malayalam</xsl:text></xsl:when>
 <xsl:when test="$code='mlt'"><xsl:text>Maltesiska</xsl:text></xsl:when>
 <xsl:when test="$code='mnc'"><xsl:text>Manchuiska</xsl:text></xsl:when>
 <xsl:when test="$code='mdr'"><xsl:text>Mandar</xsl:text></xsl:when>
 <xsl:when test="$code='man'"><xsl:text>Mandinka</xsl:text></xsl:when>
 <xsl:when test="$code='mni'"><xsl:text>Meitei</xsl:text></xsl:when>
 <xsl:when test="$code='mno'"><xsl:text>Manobospråk</xsl:text></xsl:when>
 <xsl:when test="$code='glv'"><xsl:text>Manx</xsl:text></xsl:when>
 <xsl:when test="$code='mao'"><xsl:text>Maori</xsl:text></xsl:when>
 <xsl:when test="$code='arn'"><xsl:text>Mapudungun</xsl:text></xsl:when>
 <xsl:when test="$code='mar'"><xsl:text>Marathi</xsl:text></xsl:when>
 <xsl:when test="$code='chm'"><xsl:text>Mariska</xsl:text></xsl:when>
 <xsl:when test="$code='mah'"><xsl:text>Marshallesiska</xsl:text></xsl:when>
 <xsl:when test="$code='mwr'"><xsl:text>Marwari</xsl:text></xsl:when>
 <xsl:when test="$code='mas'"><xsl:text>Maasai</xsl:text></xsl:when>
 <xsl:when test="$code='myn'"><xsl:text>Mayaspråk</xsl:text></xsl:when>
 <xsl:when test="$code='men'"><xsl:text>Mende</xsl:text></xsl:when>
 <xsl:when test="$code='mic'"><xsl:text>Mi'kmaq</xsl:text></xsl:when>
 <xsl:when test="$code='min'"><xsl:text>Minangkabau</xsl:text></xsl:when>
 <xsl:when test="$code='mwl'"><xsl:text>Mirandesiska</xsl:text></xsl:when>
 <xsl:when test="$code='mis'"><xsl:text>Övriga språk</xsl:text></xsl:when>
 <xsl:when test="$code='moh'"><xsl:text>Mohawk</xsl:text></xsl:when>
 <xsl:when test="$code='mdf'"><xsl:text>Moksja</xsl:text></xsl:when>
 <xsl:when test="$code='mkh'"><xsl:text>Mon-khmerspråk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='lol'"><xsl:text>Mongo-Nkundu</xsl:text></xsl:when>
 <xsl:when test="$code='mon'"><xsl:text>Mongoliska</xsl:text></xsl:when>
 <xsl:when test="$code='cnr'"><xsl:text>Montenegrinska</xsl:text></xsl:when>
 <xsl:when test="$code='mos'"><xsl:text>Mòoré</xsl:text></xsl:when>
 <xsl:when test="$code='mul'"><xsl:text>Flerspråkig</xsl:text></xsl:when>
 <xsl:when test="$code='mun'"><xsl:text>Mundaspråk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='nah'"><xsl:text>Nahuatl</xsl:text></xsl:when>
 <xsl:when test="$code='nau'"><xsl:text>Nauru</xsl:text></xsl:when>
 <xsl:when test="$code='nav'"><xsl:text>Navajo</xsl:text></xsl:when>
 <xsl:when test="$code='nbl'"><xsl:text>Sydndebele (Sydafrika)</xsl:text></xsl:when>
 <xsl:when test="$code='nde'"><xsl:text>Nordndebele (Zimbabwe)</xsl:text></xsl:when>
 <xsl:when test="$code='ndo'"><xsl:text>Ndonga</xsl:text></xsl:when>
 <xsl:when test="$code='nap'"><xsl:text>Neapolitanska</xsl:text></xsl:when>
 <xsl:when test="$code='nep'"><xsl:text>Nepali</xsl:text></xsl:when>
 <xsl:when test="$code='new'"><xsl:text>Newari</xsl:text></xsl:when>
 <xsl:when test="$code='nwc'"><xsl:text>Fornnewari</xsl:text></xsl:when>
 <xsl:when test="$code='nia'"><xsl:text>Nias</xsl:text></xsl:when>
 <xsl:when test="$code='nic'"><xsl:text>Niger-/Kongospråk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='ssa'"><xsl:text>Nilo-sahariska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='niu'"><xsl:text>Niuean</xsl:text></xsl:when>
 <xsl:when test="$code='nqo'"><xsl:text>N'Ko</xsl:text></xsl:when>
 <xsl:when test="$code='nog'"><xsl:text>Nogaiska</xsl:text></xsl:when>
 <xsl:when test="$code='zxx'"><xsl:text>Inget lingvistiskt innehåll </xsl:text></xsl:when>
 <xsl:when test="$code='nai'"><xsl:text>Nordamerikanska indianspråk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='frr'"><xsl:text>Nordfrisiska</xsl:text></xsl:when>
 <xsl:when test="$code='sme'"><xsl:text>Nordsamiska</xsl:text></xsl:when>
 <xsl:when test="$code='nso'"><xsl:text>Nordsotho</xsl:text></xsl:when>
 <xsl:when test="$code='nor'"><xsl:text>Norska</xsl:text></xsl:when>
 <xsl:when test="$code='nob'"><xsl:text>Norska (Bokmål)</xsl:text></xsl:when>
 <xsl:when test="$code='nno'"><xsl:text>Norska (Nynorsk)</xsl:text></xsl:when>
 <xsl:when test="$code='nub'"><xsl:text>Nubiska språk</xsl:text></xsl:when>
 <xsl:when test="$code='nym'"><xsl:text>Nyamwezi</xsl:text></xsl:when>
 <xsl:when test="$code='nya'"><xsl:text>Chichewa</xsl:text></xsl:when>
 <xsl:when test="$code='nyn'"><xsl:text>Nyankole</xsl:text></xsl:when>
 <xsl:when test="$code='nyo'"><xsl:text>Nyoro</xsl:text></xsl:when>
 <xsl:when test="$code='nzi'"><xsl:text>Nzima</xsl:text></xsl:when>
 <xsl:when test="$code='oci'"><xsl:text>Occitanska (efter 1500)</xsl:text></xsl:when>
 <xsl:when test="$code='xal'"><xsl:text>Kalmuckiska</xsl:text></xsl:when>
 <xsl:when test="$code='oji'"><xsl:text>Ojibwa</xsl:text></xsl:when>
 <xsl:when test="$code='non'"><xsl:text>Fornisländska</xsl:text></xsl:when>
 <xsl:when test="$code='peo'"><xsl:text>Fornpersiska (ca. 600-400 f.v.t.)</xsl:text></xsl:when>
 <xsl:when test="$code='ori'"><xsl:text>Oriya</xsl:text></xsl:when>
 <xsl:when test="$code='orm'"><xsl:text>Oromo</xsl:text></xsl:when>
 <xsl:when test="$code='osa'"><xsl:text>Osagespråk</xsl:text></xsl:when>
 <xsl:when test="$code='oss'"><xsl:text>Ossetiska</xsl:text></xsl:when>
 <xsl:when test="$code='oto'"><xsl:text>Otomispråk</xsl:text></xsl:when>
 <xsl:when test="$code='pal'"><xsl:text>Pahlavi</xsl:text></xsl:when>
 <xsl:when test="$code='pau'"><xsl:text>Palauiska</xsl:text></xsl:when>
 <xsl:when test="$code='pli'"><xsl:text>Pali</xsl:text></xsl:when>
 <xsl:when test="$code='pam'"><xsl:text>Pampanga</xsl:text></xsl:when>
 <xsl:when test="$code='pag'"><xsl:text>Pangasinan</xsl:text></xsl:when>
 <xsl:when test="$code='pan'"><xsl:text>Punjabi</xsl:text></xsl:when>
 <xsl:when test="$code='pap'"><xsl:text>Papiamento</xsl:text></xsl:when>
 <xsl:when test="$code='paa'"><xsl:text>Papuanska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='per'"><xsl:text>Persiska</xsl:text></xsl:when>
 <xsl:when test="$code='phi'"><xsl:text>Filippinska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='phn'"><xsl:text>Feniciska</xsl:text></xsl:when>
 <xsl:when test="$code='pon'"><xsl:text>Pohnpei</xsl:text></xsl:when>
 <xsl:when test="$code='pol'"><xsl:text>Polska</xsl:text></xsl:when>
 <xsl:when test="$code='por'"><xsl:text>Portugisiska</xsl:text></xsl:when>
 <xsl:when test="$code='pra'"><xsl:text>Prakritspråk</xsl:text></xsl:when>
 <xsl:when test="$code='pro'"><xsl:text>Provensalska (till 1500)</xsl:text></xsl:when>
 <xsl:when test="$code='pus'"><xsl:text>Pashto</xsl:text></xsl:when>
 <xsl:when test="$code='que'"><xsl:text>Quechua</xsl:text></xsl:when>
 <xsl:when test="$code='roh'"><xsl:text>Rätoromanska</xsl:text></xsl:when>
 <xsl:when test="$code='raj'"><xsl:text>Rajasthani</xsl:text></xsl:when>
 <xsl:when test="$code='rap'"><xsl:text>Rapa nui</xsl:text></xsl:when>
 <xsl:when test="$code='rar'"><xsl:text>Rarotongesiska</xsl:text></xsl:when>
 <xsl:when test="$code='roa'"><xsl:text>Romanska språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='rom'"><xsl:text>Romani</xsl:text></xsl:when>
 <xsl:when test="$code='rum'"><xsl:text>Rumänska</xsl:text></xsl:when>
 <xsl:when test="$code='run'"><xsl:text>Kirundi; Rundi</xsl:text></xsl:when>
 <xsl:when test="$code='rus'"><xsl:text>Ryska</xsl:text></xsl:when>
 <xsl:when test="$code='sal'"><xsl:text>Salishan-språk</xsl:text></xsl:when>
 <xsl:when test="$code='sam'"><xsl:text>Samarisk arameiska</xsl:text></xsl:when>
 <xsl:when test="$code='smi'"><xsl:text>Samiska</xsl:text></xsl:when>
 <xsl:when test="$code='smo'"><xsl:text>Samoanska</xsl:text></xsl:when>
 <xsl:when test="$code='sad'"><xsl:text>Sandawe</xsl:text></xsl:when>
 <xsl:when test="$code='sag'"><xsl:text>Sango (Ubangikreolska)</xsl:text></xsl:when>
 <xsl:when test="$code='san'"><xsl:text>Sanskrit</xsl:text></xsl:when>
 <xsl:when test="$code='sat'"><xsl:text>Santali</xsl:text></xsl:when>
 <xsl:when test="$code='srd'"><xsl:text>Sardiska</xsl:text></xsl:when>
 <xsl:when test="$code='sas'"><xsl:text>Sasak</xsl:text></xsl:when>
 <xsl:when test="$code='sco'"><xsl:text>Lågskotska</xsl:text></xsl:when>
 <xsl:when test="$code='gla'"><xsl:text>Skotsk gäliska</xsl:text></xsl:when>
 <xsl:when test="$code='sel'"><xsl:text>Selkup</xsl:text></xsl:when>
 <xsl:when test="$code='sem'"><xsl:text>Semitiskt språk</xsl:text></xsl:when>
 <xsl:when test="$code='srp'"><xsl:text>Serbiska</xsl:text></xsl:when>
 <xsl:when test="$code='srr'"><xsl:text>Serer</xsl:text></xsl:when>
 <xsl:when test="$code='shn'"><xsl:text>Shan</xsl:text></xsl:when>
 <xsl:when test="$code='sna'"><xsl:text>Shona</xsl:text></xsl:when>
 <xsl:when test="$code='iii'"><xsl:text>Sichuan Yi</xsl:text></xsl:when>
 <xsl:when test="$code='scn'"><xsl:text>Siciliansk italienska</xsl:text></xsl:when>
 <xsl:when test="$code='sid'"><xsl:text>Sidami</xsl:text></xsl:when>
 <xsl:when test="$code='sgn'"><xsl:text>Teckenspråk</xsl:text></xsl:when>
 <xsl:when test="$code='bla'"><xsl:text>Siksiká</xsl:text></xsl:when>
 <xsl:when test="$code='snd'"><xsl:text>Sindhi</xsl:text></xsl:when>
 <xsl:when test="$code='sin'"><xsl:text>Singalesiska</xsl:text></xsl:when>
 <xsl:when test="$code='sit'"><xsl:text>Sino-tibetanska (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='sio'"><xsl:text>Sioux-språk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='sms'"><xsl:text>Skoltsamiska</xsl:text></xsl:when>
 <xsl:when test="$code='den'"><xsl:text>Slave</xsl:text></xsl:when>
 <xsl:when test="$code='sla'"><xsl:text>Slaviska (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='slo'"><xsl:text>Slovakiska</xsl:text></xsl:when>
 <xsl:when test="$code='slv'"><xsl:text>Slovenska</xsl:text></xsl:when>
 <xsl:when test="$code='sog'"><xsl:text>Sogdiska</xsl:text></xsl:when>
 <xsl:when test="$code='som'"><xsl:text>Somaliska</xsl:text></xsl:when>
 <xsl:when test="$code='son'"><xsl:text>Songhai</xsl:text></xsl:when>
 <xsl:when test="$code='snk'"><xsl:text>Soninke</xsl:text></xsl:when>
 <xsl:when test="$code='wen'"><xsl:text>Sorbiska (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='sot'"><xsl:text>Sotho</xsl:text></xsl:when>
 <xsl:when test="$code='sai'"><xsl:text>Sydamerikanska indianspråk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='sma'"><xsl:text>Sydsamiska</xsl:text></xsl:when>
 <xsl:when test="$code='spa'"><xsl:text>Spanska</xsl:text></xsl:when>
 <xsl:when test="$code='srn'"><xsl:text>Sranan</xsl:text></xsl:when>
 <xsl:when test="$code='suk'"><xsl:text>Sukuma</xsl:text></xsl:when>
 <xsl:when test="$code='sux'"><xsl:text>Sumeriska</xsl:text></xsl:when>
 <xsl:when test="$code='sun'"><xsl:text>Sundanesiska</xsl:text></xsl:when>
 <xsl:when test="$code='sus'"><xsl:text>Susu</xsl:text></xsl:when>
 <xsl:when test="$code='swa'"><xsl:text>Swahili</xsl:text></xsl:when>
 <xsl:when test="$code='ssw'"><xsl:text>Swazi</xsl:text></xsl:when>
 <xsl:when test="$code='swe'"><xsl:text>Svenska</xsl:text></xsl:when>
 <xsl:when test="$code='gsw'"><xsl:text>Schweizertyska</xsl:text></xsl:when>
 <xsl:when test="$code='syc'"><xsl:text>Syriska, modern</xsl:text></xsl:when>
 <xsl:when test="$code='syr'"><xsl:text>Syriska, modern</xsl:text></xsl:when>
 <xsl:when test="$code='tgl'"><xsl:text>Tagalog</xsl:text></xsl:when>
 <xsl:when test="$code='tah'"><xsl:text>Tahitiska</xsl:text></xsl:when>
 <xsl:when test="$code='tai'"><xsl:text>Thaispråk (övriga)</xsl:text></xsl:when>
 <xsl:when test="$code='tgk'"><xsl:text>Tadzjikiska</xsl:text></xsl:when>
 <xsl:when test="$code='tmh'"><xsl:text>Tamashek</xsl:text></xsl:when>
 <xsl:when test="$code='tam'"><xsl:text>Tamil</xsl:text></xsl:when>
 <xsl:when test="$code='tat'"><xsl:text>Tatariska</xsl:text></xsl:when>
 <xsl:when test="$code='tel'"><xsl:text>Telugu</xsl:text></xsl:when>
 <xsl:when test="$code='tem'"><xsl:text>Temne</xsl:text></xsl:when>
 <xsl:when test="$code='ter'"><xsl:text>Terêna</xsl:text></xsl:when>
 <xsl:when test="$code='tet'"><xsl:text>Tetum</xsl:text></xsl:when>
 <xsl:when test="$code='tha'"><xsl:text>Thai</xsl:text></xsl:when>
 <xsl:when test="$code='tib'"><xsl:text>Tibetanska</xsl:text></xsl:when>
 <xsl:when test="$code='tig'"><xsl:text>Tigré</xsl:text></xsl:when>
 <xsl:when test="$code='tir'"><xsl:text>Tigrinska</xsl:text></xsl:when>
 <xsl:when test="$code='tiv'"><xsl:text>Tivi</xsl:text></xsl:when>
 <xsl:when test="$code='tli'"><xsl:text>Tlingit</xsl:text></xsl:when>
 <xsl:when test="$code='tpi'"><xsl:text>Tok Pisin</xsl:text></xsl:when>
 <xsl:when test="$code='tkl'"><xsl:text>Tokelau</xsl:text></xsl:when>
 <xsl:when test="$code='tog'"><xsl:text>Tonga</xsl:text></xsl:when>
 <xsl:when test="$code='ton'"><xsl:text>Tonga</xsl:text></xsl:when>
 <xsl:when test="$code='tsi'"><xsl:text>Tsimshian</xsl:text></xsl:when>
 <xsl:when test="$code='tso'"><xsl:text>Tsonga</xsl:text></xsl:when>
 <xsl:when test="$code='tsn'"><xsl:text>Tswana</xsl:text></xsl:when>
 <xsl:when test="$code='tum'"><xsl:text>Tumbuka</xsl:text></xsl:when>
 <xsl:when test="$code='tup'"><xsl:text>Tupí</xsl:text></xsl:when>
 <xsl:when test="$code='tur'"><xsl:text>Turkiska</xsl:text></xsl:when>
 <xsl:when test="$code='ota'"><xsl:text>Osmanska</xsl:text></xsl:when>
 <xsl:when test="$code='tuk'"><xsl:text>Turkmeniska</xsl:text></xsl:when>
 <xsl:when test="$code='tvl'"><xsl:text>Tuvaluanska</xsl:text></xsl:when>
 <xsl:when test="$code='tyv'"><xsl:text>Tuvinska</xsl:text></xsl:when>
 <xsl:when test="$code='twi'"><xsl:text>Twi</xsl:text></xsl:when>
 <xsl:when test="$code='udm'"><xsl:text>Udmurtiska</xsl:text></xsl:when>
 <xsl:when test="$code='uga'"><xsl:text>Ugaritiska</xsl:text></xsl:when>
 <xsl:when test="$code='uig'"><xsl:text>Uiguriska</xsl:text></xsl:when>
 <xsl:when test="$code='ukr'"><xsl:text>Ukrainska</xsl:text></xsl:when>
 <xsl:when test="$code='umb'"><xsl:text>Umbundu</xsl:text></xsl:when>
 <xsl:when test="$code='und'"><xsl:text>Obestämd</xsl:text></xsl:when>
 <xsl:when test="$code='hsb'"><xsl:text>Högsorbiska</xsl:text></xsl:when>
 <xsl:when test="$code='urd'"><xsl:text>Urdu</xsl:text></xsl:when>
 <xsl:when test="$code='uzb'"><xsl:text>Uzbekiska</xsl:text></xsl:when>
 <xsl:when test="$code='vai'"><xsl:text>Vai</xsl:text></xsl:when>
 <xsl:when test="$code='ven'"><xsl:text>Venda</xsl:text></xsl:when>
 <xsl:when test="$code='vie'"><xsl:text>Vietnamesiska</xsl:text></xsl:when>
 <xsl:when test="$code='vol'"><xsl:text>Volapük</xsl:text></xsl:when>
 <xsl:when test="$code='vot'"><xsl:text>Votiska</xsl:text></xsl:when>
 <xsl:when test="$code='wak'"><xsl:text>Wakashspråk</xsl:text></xsl:when>
 <xsl:when test="$code='wln'"><xsl:text>Vallonska</xsl:text></xsl:when>
 <xsl:when test="$code='war'"><xsl:text>Waray</xsl:text></xsl:when>
 <xsl:when test="$code='was'"><xsl:text>Washo</xsl:text></xsl:when>
 <xsl:when test="$code='wel'"><xsl:text>Kymriska</xsl:text></xsl:when>
 <xsl:when test="$code='him'"><xsl:text>Pahari</xsl:text></xsl:when>
 <xsl:when test="$code='wal'"><xsl:text>Walamo</xsl:text></xsl:when>
 <xsl:when test="$code='wol'"><xsl:text>Wolof</xsl:text></xsl:when>
 <xsl:when test="$code='xho'"><xsl:text>Xhosa</xsl:text></xsl:when>
 <xsl:when test="$code='sah'"><xsl:text>Jakutiska</xsl:text></xsl:when>
 <xsl:when test="$code='yao'"><xsl:text>Yao (Afrika)</xsl:text></xsl:when>
 <xsl:when test="$code='yap'"><xsl:text>Yap</xsl:text></xsl:when>
 <xsl:when test="$code='yid'"><xsl:text>Jiddisch</xsl:text></xsl:when>
 <xsl:when test="$code='yor'"><xsl:text>Yoruba</xsl:text></xsl:when>
 <xsl:when test="$code='ypk'"><xsl:text>Yupiska språk</xsl:text></xsl:when>
 <xsl:when test="$code='znd'"><xsl:text>Zandespråk</xsl:text></xsl:when>
 <xsl:when test="$code='zap'"><xsl:text>Zapotek</xsl:text></xsl:when>
 <xsl:when test="$code='zza'"><xsl:text>Zaza</xsl:text></xsl:when>
 <xsl:when test="$code='zen'"><xsl:text>Zenaga</xsl:text></xsl:when>
 <xsl:when test="$code='zha'"><xsl:text>Zhuang</xsl:text></xsl:when>
 <xsl:when test="$code='zul'"><xsl:text>Zulu</xsl:text></xsl:when>
 <xsl:when test="$code='zun'"><xsl:text>Zuni</xsl:text></xsl:when>
 <xsl:otherwise>
 <!-- when 041$a is mapped to an authorised value list, this will show the description -->
 <xsl:value-of select="$code" />
 </xsl:otherwise>
 </xsl:choose>
 </xsl:template>
</xsl:stylesheet>
