<div id="mana_comment_progress" class="alert alert-info mana_comment_status" style="display:none">
 <div id="loading"> <img src="[% interface | html %]/[% theme | html %]/img/spinner-small.gif" alt="" /> Lähetä kommentti </div>
</div>
<div id="mana_comment_success" class="alert alert-info mana_comment_status" style="display:none">
 Kommenttisi on tallennettu </div>
<div id="mana_comment_failed" class="alert alert-warning mana_comment_status" style="display:none">
 Kommenttiasi ei voitu lisätä. Yritä myöhemmin uudelleen. </div>
