<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stylesheet>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<!-- This file generated by generate_MARC21Languages.pl -->
 <xsl:template name="languageCodeText">
 <xsl:param name="code"/>
 <xsl:choose>
 <xsl:when test="$code='abk'"><xsl:text>abhaasi</xsl:text></xsl:when>
 <xsl:when test="$code='ace'"><xsl:text>aceh</xsl:text></xsl:when>
 <xsl:when test="$code='ach'"><xsl:text>atsoli</xsl:text></xsl:when>
 <xsl:when test="$code='ada'"><xsl:text>adangme</xsl:text></xsl:when>
 <xsl:when test="$code='ady'"><xsl:text>adyge</xsl:text></xsl:when>
 <xsl:when test="$code='aar'"><xsl:text>afar</xsl:text></xsl:when>
 <xsl:when test="$code='afh'"><xsl:text>afrihili (keinotekoinen kieli)</xsl:text></xsl:when>
 <xsl:when test="$code='afr'"><xsl:text>afrikaans</xsl:text></xsl:when>
 <xsl:when test="$code='afa'"><xsl:text>afroaasialaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='ain'"><xsl:text>ainu</xsl:text></xsl:when>
 <xsl:when test="$code='aka'"><xsl:text>akan</xsl:text></xsl:when>
 <xsl:when test="$code='akk'"><xsl:text>akkadi</xsl:text></xsl:when>
 <xsl:when test="$code='alb'"><xsl:text>albania</xsl:text></xsl:when>
 <xsl:when test="$code='ale'"><xsl:text>aleutti</xsl:text></xsl:when>
 <xsl:when test="$code='alg'"><xsl:text>algonkin-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='alt'"><xsl:text>altai</xsl:text></xsl:when>
 <xsl:when test="$code='tut'"><xsl:text>altailaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='amh'"><xsl:text>amhara</xsl:text></xsl:when>
 <xsl:when test="$code='anp'"><xsl:text>angika</xsl:text></xsl:when>
 <xsl:when test="$code='apa'"><xsl:text>apassikielet</xsl:text></xsl:when>
 <xsl:when test="$code='ara'"><xsl:text>arabia</xsl:text></xsl:when>
 <xsl:when test="$code='arg'"><xsl:text>aragonia</xsl:text></xsl:when>
 <xsl:when test="$code='arc'"><xsl:text>aramea</xsl:text></xsl:when>
 <xsl:when test="$code='arp'"><xsl:text>arapho</xsl:text></xsl:when>
 <xsl:when test="$code='arw'"><xsl:text>arawak</xsl:text></xsl:when>
 <xsl:when test="$code='arm'"><xsl:text>armenia</xsl:text></xsl:when>
 <xsl:when test="$code='rup'"><xsl:text>aromania</xsl:text></xsl:when>
 <xsl:when test="$code='art'"><xsl:text>keinotekoiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='asm'"><xsl:text>assami</xsl:text></xsl:when>
 <xsl:when test="$code='ath'"><xsl:text>athapasca-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='aus'"><xsl:text>australialaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='map'"><xsl:text>austronesialaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='ava'"><xsl:text>avaari</xsl:text></xsl:when>
 <xsl:when test="$code='ave'"><xsl:text>avesta</xsl:text></xsl:when>
 <xsl:when test="$code='awa'"><xsl:text>awadhi</xsl:text></xsl:when>
 <xsl:when test="$code='aym'"><xsl:text>aimara</xsl:text></xsl:when>
 <xsl:when test="$code='aze'"><xsl:text>azeri</xsl:text></xsl:when>
 <xsl:when test="$code='ast'"><xsl:text>asturia</xsl:text></xsl:when>
 <xsl:when test="$code='ban'"><xsl:text>bali</xsl:text></xsl:when>
 <xsl:when test="$code='bat'"><xsl:text>balttilaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='bal'"><xsl:text>belutsi</xsl:text></xsl:when>
 <xsl:when test="$code='bam'"><xsl:text>bambara</xsl:text></xsl:when>
 <xsl:when test="$code='bai'"><xsl:text>bamileke-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='bad'"><xsl:text>banda</xsl:text></xsl:when>
 <xsl:when test="$code='bnt'"><xsl:text>bantukielet</xsl:text></xsl:when>
 <xsl:when test="$code='bas'"><xsl:text>basa (bantukielet)</xsl:text></xsl:when>
 <xsl:when test="$code='bak'"><xsl:text>baskiiri</xsl:text></xsl:when>
 <xsl:when test="$code='baq'"><xsl:text>baski</xsl:text></xsl:when>
 <xsl:when test="$code='btk'"><xsl:text>batak</xsl:text></xsl:when>
 <xsl:when test="$code='bej'"><xsl:text>bedza</xsl:text></xsl:when>
 <xsl:when test="$code='bel'"><xsl:text>valkovenäjä</xsl:text></xsl:when>
 <xsl:when test="$code='bem'"><xsl:text>bemba</xsl:text></xsl:when>
 <xsl:when test="$code='ben'"><xsl:text>bengali</xsl:text></xsl:when>
 <xsl:when test="$code='ber'"><xsl:text>berberikielet</xsl:text></xsl:when>
 <xsl:when test="$code='bho'"><xsl:text>bhodzpuri</xsl:text></xsl:when>
 <xsl:when test="$code='bih'"><xsl:text>bihari</xsl:text></xsl:when>
 <xsl:when test="$code='bik'"><xsl:text>bikol</xsl:text></xsl:when>
 <xsl:when test="$code='byn'"><xsl:text>bilin</xsl:text></xsl:when>
 <xsl:when test="$code='bis'"><xsl:text>bislama</xsl:text></xsl:when>
 <xsl:when test="$code='zbl'"><xsl:text>Bliss-symbolit</xsl:text></xsl:when>
 <xsl:when test="$code='bos'"><xsl:text>bosnia</xsl:text></xsl:when>
 <xsl:when test="$code='bra'"><xsl:text>bradz</xsl:text></xsl:when>
 <xsl:when test="$code='bre'"><xsl:text>bretoni</xsl:text></xsl:when>
 <xsl:when test="$code='bug'"><xsl:text>bugi</xsl:text></xsl:when>
 <xsl:when test="$code='bul'"><xsl:text>bulgaria</xsl:text></xsl:when>
 <xsl:when test="$code='bua'"><xsl:text>burjaatti</xsl:text></xsl:when>
 <xsl:when test="$code='bur'"><xsl:text>burma</xsl:text></xsl:when>
 <xsl:when test="$code='cad'"><xsl:text>caddo</xsl:text></xsl:when>
 <xsl:when test="$code='car'"><xsl:text>karibi</xsl:text></xsl:when>
 <xsl:when test="$code='cat'"><xsl:text>katalaani</xsl:text></xsl:when>
 <xsl:when test="$code='cau'"><xsl:text>kaukasialaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='ceb'"><xsl:text>cebuano</xsl:text></xsl:when>
 <xsl:when test="$code='cel'"><xsl:text>kelttiläiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='cai'"><xsl:text>Keski-Amerikan intiaanikielet</xsl:text></xsl:when>
 <xsl:when test="$code='chg'"><xsl:text>tsagatai</xsl:text></xsl:when>
 <xsl:when test="$code='cmc'"><xsl:text>tsam-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='cha'"><xsl:text>tsamorro</xsl:text></xsl:when>
 <xsl:when test="$code='che'"><xsl:text>tsetseeni</xsl:text></xsl:when>
 <xsl:when test="$code='chr'"><xsl:text>cherokee</xsl:text></xsl:when>
 <xsl:when test="$code='chy'"><xsl:text>cheyenne</xsl:text></xsl:when>
 <xsl:when test="$code='chb'"><xsl:text>tsibtsa</xsl:text></xsl:when>
 <xsl:when test="$code='chi'"><xsl:text>kiina</xsl:text></xsl:when>
 <xsl:when test="$code='chn'"><xsl:text>chinook-jargon</xsl:text></xsl:when>
 <xsl:when test="$code='chp'"><xsl:text>chipewyan</xsl:text></xsl:when>
 <xsl:when test="$code='cho'"><xsl:text>chotaw</xsl:text></xsl:when>
 <xsl:when test="$code='chu'"><xsl:text>kirkkoslaavi</xsl:text></xsl:when>
 <xsl:when test="$code='chk'"><xsl:text>chuuk</xsl:text></xsl:when>
 <xsl:when test="$code='chv'"><xsl:text>tsuvassi</xsl:text></xsl:when>
 <xsl:when test="$code='cop'"><xsl:text>kopti</xsl:text></xsl:when>
 <xsl:when test="$code='cor'"><xsl:text>korni</xsl:text></xsl:when>
 <xsl:when test="$code='cos'"><xsl:text>korsika</xsl:text></xsl:when>
 <xsl:when test="$code='cre'"><xsl:text>cree</xsl:text></xsl:when>
 <xsl:when test="$code='mus'"><xsl:text>creek</xsl:text></xsl:when>
 <xsl:when test="$code='crp'"><xsl:text>kreolit ja pidginit</xsl:text></xsl:when>
 <xsl:when test="$code='cpe'"><xsl:text>englantiin perustuvat kreolit ja pidginit</xsl:text></xsl:when>
 <xsl:when test="$code='cpf'"><xsl:text>ranskaan perustuvat kreolit ja pidginit</xsl:text></xsl:when>
 <xsl:when test="$code='cpp'"><xsl:text>portugaliin perustuvat kreolit ja pidginit</xsl:text></xsl:when>
 <xsl:when test="$code='crh'"><xsl:text>krimintataari, kriminturkki</xsl:text></xsl:when>
 <xsl:when test="$code='hrv'"><xsl:text>kroatia</xsl:text></xsl:when>
 <xsl:when test="$code='cus'"><xsl:text>kuusilaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='cze'"><xsl:text>tsekki</xsl:text></xsl:when>
 <xsl:when test="$code='dak'"><xsl:text>dakota</xsl:text></xsl:when>
 <xsl:when test="$code='dan'"><xsl:text>tanska</xsl:text></xsl:when>
 <xsl:when test="$code='dar'"><xsl:text>dargi</xsl:text></xsl:when>
 <xsl:when test="$code='day'"><xsl:text>dajakki</xsl:text></xsl:when>
 <xsl:when test="$code='del'"><xsl:text>delaware</xsl:text></xsl:when>
 <xsl:when test="$code='din'"><xsl:text>dinka</xsl:text></xsl:when>
 <xsl:when test="$code='div'"><xsl:text>divehi</xsl:text></xsl:when>
 <xsl:when test="$code='doi'"><xsl:text>dogri</xsl:text></xsl:when>
 <xsl:when test="$code='dgr'"><xsl:text>dogrip</xsl:text></xsl:when>
 <xsl:when test="$code='dra'"><xsl:text>dravidakielet</xsl:text></xsl:when>
 <xsl:when test="$code='dua'"><xsl:text>duala</xsl:text></xsl:when>
 <xsl:when test="$code='dut'"><xsl:text>hollanti</xsl:text></xsl:when>
 <xsl:when test="$code='dum'"><xsl:text>keskihollanti (n. 1050-1350)</xsl:text></xsl:when>
 <xsl:when test="$code='dyu'"><xsl:text>djula</xsl:text></xsl:when>
 <xsl:when test="$code='dzo'"><xsl:text>dzongkha</xsl:text></xsl:when>
 <xsl:when test="$code='frs'"><xsl:text>itäfriisi</xsl:text></xsl:when>
 <xsl:when test="$code='bin'"><xsl:text>edo</xsl:text></xsl:when>
 <xsl:when test="$code='efi'"><xsl:text>efik</xsl:text></xsl:when>
 <xsl:when test="$code='egy'"><xsl:text>muinaisegypti</xsl:text></xsl:when>
 <xsl:when test="$code='eka'"><xsl:text>ekajuk</xsl:text></xsl:when>
 <xsl:when test="$code='elx'"><xsl:text>elami</xsl:text></xsl:when>
 <xsl:when test="$code='eng'"><xsl:text>englanti</xsl:text></xsl:when>
 <xsl:when test="$code='enm'"><xsl:text>keskienglanti (n. 1100-1500)</xsl:text></xsl:when>
 <xsl:when test="$code='ang'"><xsl:text>muinaisenglanti (n. 450-1100)</xsl:text></xsl:when>
 <xsl:when test="$code='myv'"><xsl:text>ersä</xsl:text></xsl:when>
 <xsl:when test="$code='epo'"><xsl:text>esperanto</xsl:text></xsl:when>
 <xsl:when test="$code='est'"><xsl:text>viro</xsl:text></xsl:when>
 <xsl:when test="$code='gez'"><xsl:text>ge'ez</xsl:text></xsl:when>
 <xsl:when test="$code='ewe'"><xsl:text>ewe</xsl:text></xsl:when>
 <xsl:when test="$code='ewo'"><xsl:text>ewondo</xsl:text></xsl:when>
 <xsl:when test="$code='fan'"><xsl:text>fang</xsl:text></xsl:when>
 <xsl:when test="$code='fat'"><xsl:text>fanti</xsl:text></xsl:when>
 <xsl:when test="$code='fao'"><xsl:text>fääri</xsl:text></xsl:when>
 <xsl:when test="$code='fij'"><xsl:text>fidzi</xsl:text></xsl:when>
 <xsl:when test="$code='fil'"><xsl:text>filipino</xsl:text></xsl:when>
 <xsl:when test="$code='fin'"><xsl:text>suomi</xsl:text></xsl:when>
 <xsl:when test="$code='fiu'"><xsl:text>suomalais-ugrilaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='fon'"><xsl:text>fon</xsl:text></xsl:when>
 <xsl:when test="$code='fre'"><xsl:text>ranska</xsl:text></xsl:when>
 <xsl:when test="$code='frm'"><xsl:text>keskiranska (n. 1400-1600)</xsl:text></xsl:when>
 <xsl:when test="$code='fro'"><xsl:text>muinaisranska (n. 842-1400)</xsl:text></xsl:when>
 <xsl:when test="$code='fry'"><xsl:text>friisi</xsl:text></xsl:when>
 <xsl:when test="$code='fur'"><xsl:text>friuli</xsl:text></xsl:when>
 <xsl:when test="$code='ful'"><xsl:text>fulani</xsl:text></xsl:when>
 <xsl:when test="$code='gaa'"><xsl:text>ga</xsl:text></xsl:when>
 <xsl:when test="$code='glg'"><xsl:text>galicia</xsl:text></xsl:when>
 <xsl:when test="$code='lug'"><xsl:text>ganda</xsl:text></xsl:when>
 <xsl:when test="$code='gay'"><xsl:text>gajo</xsl:text></xsl:when>
 <xsl:when test="$code='gba'"><xsl:text>gbaja</xsl:text></xsl:when>
 <xsl:when test="$code='geo'"><xsl:text>georgia</xsl:text></xsl:when>
 <xsl:when test="$code='ger'"><xsl:text>saksa</xsl:text></xsl:when>
 <xsl:when test="$code='gmh'"><xsl:text>keskiyläsaksa (n. 1050-1500)</xsl:text></xsl:when>
 <xsl:when test="$code='goh'"><xsl:text>muinaisyläsaksa (n. 750-1050)</xsl:text></xsl:when>
 <xsl:when test="$code='gem'"><xsl:text>germaaniset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='gil'"><xsl:text>kiribati</xsl:text></xsl:when>
 <xsl:when test="$code='gon'"><xsl:text>gondi</xsl:text></xsl:when>
 <xsl:when test="$code='gor'"><xsl:text>gorontalo</xsl:text></xsl:when>
 <xsl:when test="$code='got'"><xsl:text>gootti</xsl:text></xsl:when>
 <xsl:when test="$code='grb'"><xsl:text>grebo</xsl:text></xsl:when>
 <xsl:when test="$code='grc'"><xsl:text>muinaiskreikka (-1453)</xsl:text></xsl:when>
 <xsl:when test="$code='gre'"><xsl:text>kreikka (1453-)</xsl:text></xsl:when>
 <xsl:when test="$code='grn'"><xsl:text>guarani</xsl:text></xsl:when>
 <xsl:when test="$code='guj'"><xsl:text>gudzarati</xsl:text></xsl:when>
 <xsl:when test="$code='gwi'"><xsl:text>gwitsin</xsl:text></xsl:when>
 <xsl:when test="$code='hai'"><xsl:text>haida</xsl:text></xsl:when>
 <xsl:when test="$code='hat'"><xsl:text>haiti</xsl:text></xsl:when>
 <xsl:when test="$code='hau'"><xsl:text>hausa</xsl:text></xsl:when>
 <xsl:when test="$code='haw'"><xsl:text>havaji</xsl:text></xsl:when>
 <xsl:when test="$code='heb'"><xsl:text>heprea</xsl:text></xsl:when>
 <xsl:when test="$code='her'"><xsl:text>herero</xsl:text></xsl:when>
 <xsl:when test="$code='hil'"><xsl:text>hiligaino</xsl:text></xsl:when>
 <xsl:when test="$code='hin'"><xsl:text>hindi</xsl:text></xsl:when>
 <xsl:when test="$code='hmo'"><xsl:text>hiri-motu</xsl:text></xsl:when>
 <xsl:when test="$code='hit'"><xsl:text>heetti</xsl:text></xsl:when>
 <xsl:when test="$code='hmn'"><xsl:text>hmong</xsl:text></xsl:when>
 <xsl:when test="$code='hun'"><xsl:text>unkari</xsl:text></xsl:when>
 <xsl:when test="$code='hup'"><xsl:text>hupa</xsl:text></xsl:when>
 <xsl:when test="$code='iba'"><xsl:text>iban</xsl:text></xsl:when>
 <xsl:when test="$code='ice'"><xsl:text>islanti</xsl:text></xsl:when>
 <xsl:when test="$code='ido'"><xsl:text>ido</xsl:text></xsl:when>
 <xsl:when test="$code='ibo'"><xsl:text>igbo</xsl:text></xsl:when>
 <xsl:when test="$code='ijo'"><xsl:text>idzo</xsl:text></xsl:when>
 <xsl:when test="$code='ilo'"><xsl:text>iloko</xsl:text></xsl:when>
 <xsl:when test="$code='smn'"><xsl:text>saame, inarin-</xsl:text></xsl:when>
 <xsl:when test="$code='inc'"><xsl:text>indoarjalaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='ine'"><xsl:text>indoeurooppalaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='ind'"><xsl:text>indonesia</xsl:text></xsl:when>
 <xsl:when test="$code='inh'"><xsl:text>inguusi</xsl:text></xsl:when>
 <xsl:when test="$code='ina'"><xsl:text>interlingua</xsl:text></xsl:when>
 <xsl:when test="$code='ile'"><xsl:text>interlingue</xsl:text></xsl:when>
 <xsl:when test="$code='iku'"><xsl:text>inuktitut</xsl:text></xsl:when>
 <xsl:when test="$code='ipk'"><xsl:text>inupiatun</xsl:text></xsl:when>
 <xsl:when test="$code='ira'"><xsl:text>iranilaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='gle'"><xsl:text>iiri</xsl:text></xsl:when>
 <xsl:when test="$code='mga'"><xsl:text>keski-iiri (n. 1100-1550)</xsl:text></xsl:when>
 <xsl:when test="$code='sga'"><xsl:text>muinaisiiri (-1100)</xsl:text></xsl:when>
 <xsl:when test="$code='iro'"><xsl:text>irokeesikielet</xsl:text></xsl:when>
 <xsl:when test="$code='ita'"><xsl:text>italia</xsl:text></xsl:when>
 <xsl:when test="$code='jpn'"><xsl:text>japani</xsl:text></xsl:when>
 <xsl:when test="$code='jav'"><xsl:text>jaava</xsl:text></xsl:when>
 <xsl:when test="$code='jrb'"><xsl:text>juutalaisarabia</xsl:text></xsl:when>
 <xsl:when test="$code='jpr'"><xsl:text>juutalaispersia</xsl:text></xsl:when>
 <xsl:when test="$code='kbd'"><xsl:text>kabardi</xsl:text></xsl:when>
 <xsl:when test="$code='kab'"><xsl:text>kabyyli</xsl:text></xsl:when>
 <xsl:when test="$code='kac'"><xsl:text>kachin</xsl:text></xsl:when>
 <xsl:when test="$code='kal'"><xsl:text>kalaallisut, grönlanti</xsl:text></xsl:when>
 <xsl:when test="$code='kam'"><xsl:text>kamba</xsl:text></xsl:when>
 <xsl:when test="$code='kan'"><xsl:text>kannada</xsl:text></xsl:when>
 <xsl:when test="$code='kau'"><xsl:text>kanuri</xsl:text></xsl:when>
 <xsl:when test="$code='krc'"><xsl:text>karatsai-balkaari</xsl:text></xsl:when>
 <xsl:when test="$code='kaa'"><xsl:text>karakalpakki</xsl:text></xsl:when>
 <xsl:when test="$code='krl'"><xsl:text>karjala</xsl:text></xsl:when>
 <xsl:when test="$code='kar'"><xsl:text>karen</xsl:text></xsl:when>
 <xsl:when test="$code='kas'"><xsl:text>kasmiri</xsl:text></xsl:when>
 <xsl:when test="$code='csb'"><xsl:text>kasubi</xsl:text></xsl:when>
 <xsl:when test="$code='kaw'"><xsl:text>kavi</xsl:text></xsl:when>
 <xsl:when test="$code='kaz'"><xsl:text>kazakki</xsl:text></xsl:when>
 <xsl:when test="$code='kha'"><xsl:text>khasi</xsl:text></xsl:when>
 <xsl:when test="$code='khm'"><xsl:text>khmer</xsl:text></xsl:when>
 <xsl:when test="$code='khi'"><xsl:text>khoisan-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='kho'"><xsl:text>khotani</xsl:text></xsl:when>
 <xsl:when test="$code='kik'"><xsl:text>kikuju</xsl:text></xsl:when>
 <xsl:when test="$code='kmb'"><xsl:text>kimbundu</xsl:text></xsl:when>
 <xsl:when test="$code='kin'"><xsl:text>ruanda</xsl:text></xsl:when>
 <xsl:when test="$code='tlh'"><xsl:text>klingon (keinotekoinen kieli)</xsl:text></xsl:when>
 <xsl:when test="$code='kom'"><xsl:text>komi</xsl:text></xsl:when>
 <xsl:when test="$code='kon'"><xsl:text>kongo</xsl:text></xsl:when>
 <xsl:when test="$code='kok'"><xsl:text>konkani</xsl:text></xsl:when>
 <xsl:when test="$code='kut'"><xsl:text>kutenai</xsl:text></xsl:when>
 <xsl:when test="$code='kor'"><xsl:text>korea</xsl:text></xsl:when>
 <xsl:when test="$code='kos'"><xsl:text>kosrae</xsl:text></xsl:when>
 <xsl:when test="$code='kpe'"><xsl:text>kpelle</xsl:text></xsl:when>
 <xsl:when test="$code='kro'"><xsl:text>kru-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='kua'"><xsl:text>kuanjama</xsl:text></xsl:when>
 <xsl:when test="$code='kum'"><xsl:text>kumykki</xsl:text></xsl:when>
 <xsl:when test="$code='kur'"><xsl:text>kurdi</xsl:text></xsl:when>
 <xsl:when test="$code='kru'"><xsl:text>kurukh</xsl:text></xsl:when>
 <xsl:when test="$code='kir'"><xsl:text>kirgiisi</xsl:text></xsl:when>
 <xsl:when test="$code='lad'"><xsl:text>ladino, juutalaisespanja</xsl:text></xsl:when>
 <xsl:when test="$code='lah'"><xsl:text>lahnda</xsl:text></xsl:when>
 <xsl:when test="$code='lam'"><xsl:text>lamda</xsl:text></xsl:when>
 <xsl:when test="$code='lao'"><xsl:text>lao</xsl:text></xsl:when>
 <xsl:when test="$code='lat'"><xsl:text>latina</xsl:text></xsl:when>
 <xsl:when test="$code='lav'"><xsl:text>latvia</xsl:text></xsl:when>
 <xsl:when test="$code='lez'"><xsl:text>lezgi</xsl:text></xsl:when>
 <xsl:when test="$code='lim'"><xsl:text>limburg</xsl:text></xsl:when>
 <xsl:when test="$code='lin'"><xsl:text>lingala</xsl:text></xsl:when>
 <xsl:when test="$code='lit'"><xsl:text>liettua</xsl:text></xsl:when>
 <xsl:when test="$code='jbo'"><xsl:text>lojban (keinotekoinen kieli)</xsl:text></xsl:when>
 <xsl:when test="$code='nds'"><xsl:text>alasaksa</xsl:text></xsl:when>
 <xsl:when test="$code='dsb'"><xsl:text>alasorbi</xsl:text></xsl:when>
 <xsl:when test="$code='loz'"><xsl:text>lozi</xsl:text></xsl:when>
 <xsl:when test="$code='lub'"><xsl:text>luba (Katanga)</xsl:text></xsl:when>
 <xsl:when test="$code='lua'"><xsl:text>luba (Lulua)</xsl:text></xsl:when>
 <xsl:when test="$code='lui'"><xsl:text>luiseno</xsl:text></xsl:when>
 <xsl:when test="$code='smj'"><xsl:text>saame, luulajan-</xsl:text></xsl:when>
 <xsl:when test="$code='lun'"><xsl:text>lunda</xsl:text></xsl:when>
 <xsl:when test="$code='luo'"><xsl:text>luo</xsl:text></xsl:when>
 <xsl:when test="$code='lus'"><xsl:text>lusai</xsl:text></xsl:when>
 <xsl:when test="$code='ltz'"><xsl:text>luxemburg</xsl:text></xsl:when>
 <xsl:when test="$code='mac'"><xsl:text>makedonia</xsl:text></xsl:when>
 <xsl:when test="$code='mad'"><xsl:text>madura</xsl:text></xsl:when>
 <xsl:when test="$code='mag'"><xsl:text>magahi</xsl:text></xsl:when>
 <xsl:when test="$code='mai'"><xsl:text>maithili</xsl:text></xsl:when>
 <xsl:when test="$code='mak'"><xsl:text>makassar</xsl:text></xsl:when>
 <xsl:when test="$code='mlg'"><xsl:text>malagassi</xsl:text></xsl:when>
 <xsl:when test="$code='may'"><xsl:text>malaiji</xsl:text></xsl:when>
 <xsl:when test="$code='mal'"><xsl:text>malajalam</xsl:text></xsl:when>
 <xsl:when test="$code='mlt'"><xsl:text>malta</xsl:text></xsl:when>
 <xsl:when test="$code='mnc'"><xsl:text>mantsu</xsl:text></xsl:when>
 <xsl:when test="$code='mdr'"><xsl:text>mandar</xsl:text></xsl:when>
 <xsl:when test="$code='man'"><xsl:text>mandingo</xsl:text></xsl:when>
 <xsl:when test="$code='mni'"><xsl:text>manipuri</xsl:text></xsl:when>
 <xsl:when test="$code='mno'"><xsl:text>manobo-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='glv'"><xsl:text>manx</xsl:text></xsl:when>
 <xsl:when test="$code='mao'"><xsl:text>maori</xsl:text></xsl:when>
 <xsl:when test="$code='arn'"><xsl:text>mapuche</xsl:text></xsl:when>
 <xsl:when test="$code='mar'"><xsl:text>marathi</xsl:text></xsl:when>
 <xsl:when test="$code='chm'"><xsl:text>mari</xsl:text></xsl:when>
 <xsl:when test="$code='mah'"><xsl:text>marshall</xsl:text></xsl:when>
 <xsl:when test="$code='mwr'"><xsl:text>marwari</xsl:text></xsl:when>
 <xsl:when test="$code='mas'"><xsl:text>maasai</xsl:text></xsl:when>
 <xsl:when test="$code='myn'"><xsl:text>maya-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='men'"><xsl:text>mende</xsl:text></xsl:when>
 <xsl:when test="$code='mic'"><xsl:text>micmac</xsl:text></xsl:when>
 <xsl:when test="$code='min'"><xsl:text>minangkabau</xsl:text></xsl:when>
 <xsl:when test="$code='mwl'"><xsl:text>mirandeesi</xsl:text></xsl:when>
 <xsl:when test="$code='mis'"><xsl:text>luokittelemattomat kielet</xsl:text></xsl:when>
 <xsl:when test="$code='moh'"><xsl:text>mohawk</xsl:text></xsl:when>
 <xsl:when test="$code='mdf'"><xsl:text>moksa</xsl:text></xsl:when>
 <xsl:when test="$code='mkh'"><xsl:text>mon-khmer-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='lol'"><xsl:text>mongo</xsl:text></xsl:when>
 <xsl:when test="$code='mon'"><xsl:text>mongoli</xsl:text></xsl:when>
 <xsl:when test="$code='cnr'"><xsl:text>montenegrin</xsl:text></xsl:when>
 <xsl:when test="$code='mos'"><xsl:text>mossi</xsl:text></xsl:when>
 <xsl:when test="$code='mul'"><xsl:text>Useita kieliä</xsl:text></xsl:when>
 <xsl:when test="$code='mun'"><xsl:text>munda-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='nah'"><xsl:text>nahuatl</xsl:text></xsl:when>
 <xsl:when test="$code='nau'"><xsl:text>Nauru</xsl:text></xsl:when>
 <xsl:when test="$code='nav'"><xsl:text>navajo</xsl:text></xsl:when>
 <xsl:when test="$code='nbl'"><xsl:text>etelä-ndebele</xsl:text></xsl:when>
 <xsl:when test="$code='nde'"><xsl:text>pohjois-ndebele</xsl:text></xsl:when>
 <xsl:when test="$code='ndo'"><xsl:text>ndonga</xsl:text></xsl:when>
 <xsl:when test="$code='nap'"><xsl:text>napoli</xsl:text></xsl:when>
 <xsl:when test="$code='nep'"><xsl:text>nepali</xsl:text></xsl:when>
 <xsl:when test="$code='new'"><xsl:text>newari</xsl:text></xsl:when>
 <xsl:when test="$code='nwc'"><xsl:text>klassinen newari</xsl:text></xsl:when>
 <xsl:when test="$code='nia'"><xsl:text>nias</xsl:text></xsl:when>
 <xsl:when test="$code='nic'"><xsl:text>nigeriläis-kongolaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='ssa'"><xsl:text>niililäis-saharalaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='niu'"><xsl:text>niue</xsl:text></xsl:when>
 <xsl:when test="$code='nqo'"><xsl:text>n'ko</xsl:text></xsl:when>
 <xsl:when test="$code='nog'"><xsl:text>nogai</xsl:text></xsl:when>
 <xsl:when test="$code='zxx'"><xsl:text>Ei kielellistä sisältöä, soveltumaton</xsl:text></xsl:when>
 <xsl:when test="$code='nai'"><xsl:text>Pohjois-Amerikan intiaanikielet</xsl:text></xsl:when>
 <xsl:when test="$code='frr'"><xsl:text>pohjoisfriisi</xsl:text></xsl:when>
 <xsl:when test="$code='sme'"><xsl:text>pohjoissaame</xsl:text></xsl:when>
 <xsl:when test="$code='nso'"><xsl:text>pohjoissotho</xsl:text></xsl:when>
 <xsl:when test="$code='nor'"><xsl:text>norja</xsl:text></xsl:when>
 <xsl:when test="$code='nob'"><xsl:text>norja, bokmål</xsl:text></xsl:when>
 <xsl:when test="$code='nno'"><xsl:text>norja, nynorsk</xsl:text></xsl:when>
 <xsl:when test="$code='nub'"><xsl:text>nubialaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='nym'"><xsl:text>nyamwezi</xsl:text></xsl:when>
 <xsl:when test="$code='nya'"><xsl:text>njandza</xsl:text></xsl:when>
 <xsl:when test="$code='nyn'"><xsl:text>nyankole</xsl:text></xsl:when>
 <xsl:when test="$code='nyo'"><xsl:text>nyoro</xsl:text></xsl:when>
 <xsl:when test="$code='nzi'"><xsl:text>nzima</xsl:text></xsl:when>
 <xsl:when test="$code='oci'"><xsl:text>oksitaani (1500-)</xsl:text></xsl:when>
 <xsl:when test="$code='xal'"><xsl:text>oirat</xsl:text></xsl:when>
 <xsl:when test="$code='oji'"><xsl:text>odzibwa</xsl:text></xsl:when>
 <xsl:when test="$code='non'"><xsl:text>muinaisnorja</xsl:text></xsl:when>
 <xsl:when test="$code='peo'"><xsl:text>muinaispersia (n. 600-400 eKr.)</xsl:text></xsl:when>
 <xsl:when test="$code='ori'"><xsl:text>orija</xsl:text></xsl:when>
 <xsl:when test="$code='orm'"><xsl:text>oromo</xsl:text></xsl:when>
 <xsl:when test="$code='osa'"><xsl:text>osage</xsl:text></xsl:when>
 <xsl:when test="$code='oss'"><xsl:text>osseetti</xsl:text></xsl:when>
 <xsl:when test="$code='oto'"><xsl:text>otomi-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='pal'"><xsl:text>pahlavi</xsl:text></xsl:when>
 <xsl:when test="$code='pau'"><xsl:text>palau</xsl:text></xsl:when>
 <xsl:when test="$code='pli'"><xsl:text>paali</xsl:text></xsl:when>
 <xsl:when test="$code='pam'"><xsl:text>pampanga</xsl:text></xsl:when>
 <xsl:when test="$code='pag'"><xsl:text>pangasinan</xsl:text></xsl:when>
 <xsl:when test="$code='pan'"><xsl:text>pandzabi</xsl:text></xsl:when>
 <xsl:when test="$code='pap'"><xsl:text>papiamentu</xsl:text></xsl:when>
 <xsl:when test="$code='paa'"><xsl:text>papualaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='per'"><xsl:text>farsi, persia</xsl:text></xsl:when>
 <xsl:when test="$code='phi'"><xsl:text>filippiiniläiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='phn'"><xsl:text>foinikia</xsl:text></xsl:when>
 <xsl:when test="$code='pon'"><xsl:text>pohnpei</xsl:text></xsl:when>
 <xsl:when test="$code='pol'"><xsl:text>puola</xsl:text></xsl:when>
 <xsl:when test="$code='por'"><xsl:text>portugali</xsl:text></xsl:when>
 <xsl:when test="$code='pra'"><xsl:text>prakit-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='pro'"><xsl:text>muinaisprovensaali (-1500)</xsl:text></xsl:when>
 <xsl:when test="$code='pus'"><xsl:text>pastu</xsl:text></xsl:when>
 <xsl:when test="$code='que'"><xsl:text>ketsua</xsl:text></xsl:when>
 <xsl:when test="$code='roh'"><xsl:text>raeto-romance</xsl:text></xsl:when>
 <xsl:when test="$code='raj'"><xsl:text>radzastani</xsl:text></xsl:when>
 <xsl:when test="$code='rap'"><xsl:text>rapanui</xsl:text></xsl:when>
 <xsl:when test="$code='rar'"><xsl:text>rarotonga</xsl:text></xsl:when>
 <xsl:when test="$code='roa'"><xsl:text>romaaniset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='rom'"><xsl:text>romani</xsl:text></xsl:when>
 <xsl:when test="$code='rum'"><xsl:text>romania</xsl:text></xsl:when>
 <xsl:when test="$code='run'"><xsl:text>rundi</xsl:text></xsl:when>
 <xsl:when test="$code='rus'"><xsl:text>venäjä</xsl:text></xsl:when>
 <xsl:when test="$code='sal'"><xsl:text>salisialaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='sam'"><xsl:text>samarianaramea</xsl:text></xsl:when>
 <xsl:when test="$code='smi'"><xsl:text>saamelaiskielet</xsl:text></xsl:when>
 <xsl:when test="$code='smo'"><xsl:text>samoa</xsl:text></xsl:when>
 <xsl:when test="$code='sad'"><xsl:text>sandawe</xsl:text></xsl:when>
 <xsl:when test="$code='sag'"><xsl:text>sango</xsl:text></xsl:when>
 <xsl:when test="$code='san'"><xsl:text>sanskrit</xsl:text></xsl:when>
 <xsl:when test="$code='sat'"><xsl:text>santali</xsl:text></xsl:when>
 <xsl:when test="$code='srd'"><xsl:text>sardi</xsl:text></xsl:when>
 <xsl:when test="$code='sas'"><xsl:text>sasak</xsl:text></xsl:when>
 <xsl:when test="$code='sco'"><xsl:text>skotti</xsl:text></xsl:when>
 <xsl:when test="$code='gla'"><xsl:text>gaeli</xsl:text></xsl:when>
 <xsl:when test="$code='sel'"><xsl:text>selkuppi</xsl:text></xsl:when>
 <xsl:when test="$code='sem'"><xsl:text>seemiläiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='srp'"><xsl:text>serbia</xsl:text></xsl:when>
 <xsl:when test="$code='srr'"><xsl:text>serer</xsl:text></xsl:when>
 <xsl:when test="$code='shn'"><xsl:text>shan</xsl:text></xsl:when>
 <xsl:when test="$code='sna'"><xsl:text>sona</xsl:text></xsl:when>
 <xsl:when test="$code='iii'"><xsl:text>sichuannin-yi</xsl:text></xsl:when>
 <xsl:when test="$code='scn'"><xsl:text>sisilia</xsl:text></xsl:when>
 <xsl:when test="$code='sid'"><xsl:text>sidamo</xsl:text></xsl:when>
 <xsl:when test="$code='sgn'"><xsl:text>Viittomakielet</xsl:text></xsl:when>
 <xsl:when test="$code='bla'"><xsl:text>mustajalka</xsl:text></xsl:when>
 <xsl:when test="$code='snd'"><xsl:text>sindhi</xsl:text></xsl:when>
 <xsl:when test="$code='sin'"><xsl:text>sinhali</xsl:text></xsl:when>
 <xsl:when test="$code='sit'"><xsl:text>sinotiibetiläiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='sio'"><xsl:text>sioux-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='sms'"><xsl:text>saame, koltan-</xsl:text></xsl:when>
 <xsl:when test="$code='den'"><xsl:text>slevi</xsl:text></xsl:when>
 <xsl:when test="$code='sla'"><xsl:text>slaavilaiset kielet</xsl:text></xsl:when>
 <xsl:when test="$code='slo'"><xsl:text>slovakki</xsl:text></xsl:when>
 <xsl:when test="$code='slv'"><xsl:text>sloveeni</xsl:text></xsl:when>
 <xsl:when test="$code='sog'"><xsl:text>sogdi</xsl:text></xsl:when>
 <xsl:when test="$code='som'"><xsl:text>somali</xsl:text></xsl:when>
 <xsl:when test="$code='son'"><xsl:text>songhai</xsl:text></xsl:when>
 <xsl:when test="$code='snk'"><xsl:text>soninke</xsl:text></xsl:when>
 <xsl:when test="$code='wen'"><xsl:text>sorbin kielet</xsl:text></xsl:when>
 <xsl:when test="$code='sot'"><xsl:text>sotho</xsl:text></xsl:when>
 <xsl:when test="$code='sai'"><xsl:text>Etelä-Amerikan intiaanikielet</xsl:text></xsl:when>
 <xsl:when test="$code='sma'"><xsl:text>eteläsaame</xsl:text></xsl:when>
 <xsl:when test="$code='spa'"><xsl:text>espanja</xsl:text></xsl:when>
 <xsl:when test="$code='srn'"><xsl:text>sranan</xsl:text></xsl:when>
 <xsl:when test="$code='suk'"><xsl:text>sukuma</xsl:text></xsl:when>
 <xsl:when test="$code='sux'"><xsl:text>sumeri</xsl:text></xsl:when>
 <xsl:when test="$code='sun'"><xsl:text>sunda</xsl:text></xsl:when>
 <xsl:when test="$code='sus'"><xsl:text>susu</xsl:text></xsl:when>
 <xsl:when test="$code='swa'"><xsl:text>swahili</xsl:text></xsl:when>
 <xsl:when test="$code='ssw'"><xsl:text>Etiopia</xsl:text></xsl:when>
 <xsl:when test="$code='swe'"><xsl:text>ruotsi</xsl:text></xsl:when>
 <xsl:when test="$code='gsw'"><xsl:text>sveitsinsaksa</xsl:text></xsl:when>
 <xsl:when test="$code='syc'"><xsl:text>muinaissyyria</xsl:text></xsl:when>
 <xsl:when test="$code='syr'"><xsl:text>syyria</xsl:text></xsl:when>
 <xsl:when test="$code='tgl'"><xsl:text>tagalog</xsl:text></xsl:when>
 <xsl:when test="$code='tah'"><xsl:text>tahiti</xsl:text></xsl:when>
 <xsl:when test="$code='tai'"><xsl:text>thaikielet</xsl:text></xsl:when>
 <xsl:when test="$code='tgk'"><xsl:text>tadzikki</xsl:text></xsl:when>
 <xsl:when test="$code='tmh'"><xsl:text>tamasek</xsl:text></xsl:when>
 <xsl:when test="$code='tam'"><xsl:text>tamili</xsl:text></xsl:when>
 <xsl:when test="$code='tat'"><xsl:text>tataari</xsl:text></xsl:when>
 <xsl:when test="$code='tel'"><xsl:text>telugu</xsl:text></xsl:when>
 <xsl:when test="$code='tem'"><xsl:text>temne</xsl:text></xsl:when>
 <xsl:when test="$code='ter'"><xsl:text>tereno</xsl:text></xsl:when>
 <xsl:when test="$code='tet'"><xsl:text>tetum</xsl:text></xsl:when>
 <xsl:when test="$code='tha'"><xsl:text>thai</xsl:text></xsl:when>
 <xsl:when test="$code='tib'"><xsl:text>tiibet</xsl:text></xsl:when>
 <xsl:when test="$code='tig'"><xsl:text>tigre</xsl:text></xsl:when>
 <xsl:when test="$code='tir'"><xsl:text>tigrinja</xsl:text></xsl:when>
 <xsl:when test="$code='tiv'"><xsl:text>tiv</xsl:text></xsl:when>
 <xsl:when test="$code='tli'"><xsl:text>tlingit</xsl:text></xsl:when>
 <xsl:when test="$code='tpi'"><xsl:text>tok-pisin</xsl:text></xsl:when>
 <xsl:when test="$code='tkl'"><xsl:text>tokelau</xsl:text></xsl:when>
 <xsl:when test="$code='tog'"><xsl:text>tonga (Malawi)</xsl:text></xsl:when>
 <xsl:when test="$code='ton'"><xsl:text>tonga (Tonga)</xsl:text></xsl:when>
 <xsl:when test="$code='tsi'"><xsl:text>tsimsi</xsl:text></xsl:when>
 <xsl:when test="$code='tso'"><xsl:text>tsonga</xsl:text></xsl:when>
 <xsl:when test="$code='tsn'"><xsl:text>tswana</xsl:text></xsl:when>
 <xsl:when test="$code='tum'"><xsl:text>tumbuka</xsl:text></xsl:when>
 <xsl:when test="$code='tup'"><xsl:text>tupi-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='tur'"><xsl:text>turkki</xsl:text></xsl:when>
 <xsl:when test="$code='ota'"><xsl:text>osmani (1500-1928)</xsl:text></xsl:when>
 <xsl:when test="$code='tuk'"><xsl:text>turkmeeni</xsl:text></xsl:when>
 <xsl:when test="$code='tvl'"><xsl:text>tuvalu</xsl:text></xsl:when>
 <xsl:when test="$code='tyv'"><xsl:text>tuva</xsl:text></xsl:when>
 <xsl:when test="$code='twi'"><xsl:text>twi</xsl:text></xsl:when>
 <xsl:when test="$code='udm'"><xsl:text>udmurtti</xsl:text></xsl:when>
 <xsl:when test="$code='uga'"><xsl:text>ugarit</xsl:text></xsl:when>
 <xsl:when test="$code='uig'"><xsl:text>uiguuri</xsl:text></xsl:when>
 <xsl:when test="$code='ukr'"><xsl:text>ukraina</xsl:text></xsl:when>
 <xsl:when test="$code='umb'"><xsl:text>umbundu</xsl:text></xsl:when>
 <xsl:when test="$code='und'"><xsl:text>Ei määritelty</xsl:text></xsl:when>
 <xsl:when test="$code='hsb'"><xsl:text>yläsorbi</xsl:text></xsl:when>
 <xsl:when test="$code='urd'"><xsl:text>urdu</xsl:text></xsl:when>
 <xsl:when test="$code='uzb'"><xsl:text>uzbekki</xsl:text></xsl:when>
 <xsl:when test="$code='vai'"><xsl:text>vai</xsl:text></xsl:when>
 <xsl:when test="$code='ven'"><xsl:text>venda</xsl:text></xsl:when>
 <xsl:when test="$code='vie'"><xsl:text>vietnam</xsl:text></xsl:when>
 <xsl:when test="$code='vol'"><xsl:text>volapük</xsl:text></xsl:when>
 <xsl:when test="$code='vot'"><xsl:text>vatja</xsl:text></xsl:when>
 <xsl:when test="$code='wak'"><xsl:text>wakash-kielet</xsl:text></xsl:when>
 <xsl:when test="$code='wln'"><xsl:text>valloni</xsl:text></xsl:when>
 <xsl:when test="$code='war'"><xsl:text>waray</xsl:text></xsl:when>
 <xsl:when test="$code='was'"><xsl:text>washo</xsl:text></xsl:when>
 <xsl:when test="$code='wel'"><xsl:text>kymri</xsl:text></xsl:when>
 <xsl:when test="$code='him'"><xsl:text>himatsali</xsl:text></xsl:when>
 <xsl:when test="$code='wal'"><xsl:text>walamo</xsl:text></xsl:when>
 <xsl:when test="$code='wol'"><xsl:text>wolof</xsl:text></xsl:when>
 <xsl:when test="$code='xho'"><xsl:text>xhosa</xsl:text></xsl:when>
 <xsl:when test="$code='sah'"><xsl:text>jakuutti</xsl:text></xsl:when>
 <xsl:when test="$code='yao'"><xsl:text>jao</xsl:text></xsl:when>
 <xsl:when test="$code='yap'"><xsl:text>japi</xsl:text></xsl:when>
 <xsl:when test="$code='yid'"><xsl:text>jiddis</xsl:text></xsl:when>
 <xsl:when test="$code='yor'"><xsl:text>joruba</xsl:text></xsl:when>
 <xsl:when test="$code='ypk'"><xsl:text>jupikkikielet</xsl:text></xsl:when>
 <xsl:when test="$code='znd'"><xsl:text>zande</xsl:text></xsl:when>
 <xsl:when test="$code='zap'"><xsl:text>sapoteekki</xsl:text></xsl:when>
 <xsl:when test="$code='zza'"><xsl:text>zaza</xsl:text></xsl:when>
 <xsl:when test="$code='zen'"><xsl:text>zenaga</xsl:text></xsl:when>
 <xsl:when test="$code='zha'"><xsl:text>zhuang</xsl:text></xsl:when>
 <xsl:when test="$code='zul'"><xsl:text>zulu</xsl:text></xsl:when>
 <xsl:when test="$code='zun'"><xsl:text>zuni</xsl:text></xsl:when>
 <xsl:otherwise>
 <!-- when 041$a is mapped to an authorised value list, this will show the description -->
 <xsl:value-of select="$code" />
 </xsl:otherwise>
 </xsl:choose>
 </xsl:template>
</xsl:stylesheet>
