<div id="ArticleRequestsDisclaimerText_notes" class="hint customization_note">
 Information som visas för OPACanvändare innan de kan göra en artikelbeställning. </div>

<div id="CatalogConcernHelp_notes"  class="hint customization_note">
 Inkludera denna information i det formulär som visas i OPAC när en användare gör en felanmälan angående katalogen. </div>

<div id="CatalogConcernTemplate_notes"  class="hint customization_note">
 Fyll i OPAC-katalogformuläret i förväg med detta innehåll som en mall för användarens bidrag. </div>

<div id="CookieConsentBar_notes"  class="hint customization_note">
 Inkludera denna information i cookie-inställningarna som visas i OPACens sidfot när systeminställningen CookieConsent är aktiverad. </div>

<div id="CookieConsentPopup_notes"  class="hint customization_note">
 Inkludera denna information i popup-meddelandet som visas i OPAC när systeminställningen CookieConsent är aktiverad och användaren klickar på alternativet "Hantera Cookies" i sidhuvudet. </div>

<div id="ILLModuleCopyrightClearance_notes" class="hint customization_note">
 Adding content to this region will enable the copyright clearance stage in request creation. The content will appear on the OPAC during the process of placing an ILL request.
</div>

<div id="IntranetmainUserblock_notes" class="hint customization_note">
 Visa det här innehållet i en egen kolumn på förstasidan i personalgränssnittet </div>

<div id="opaccredits_notes" class="hint customization_note">
 Inkludera följande innehåll i sidfoten på alla sidor i OPAC. </div>

<div id="OpacCustomSearch_notes" class="hint customization_note">
 Ersätt sökrutan högst upp i OPAC med följande innehåll. </div>

<div id="opacheader_notes" class="hint customization_note">
 Inkludera följande innehåll i sidhuvudet på alla sidor i OPAC. </div>

<div id="OpacLibraryInfo_notes" class="hint customization_note">
 Inkludera detta innehåll på sidan med biblioteksinformation i OPAC. </div>

<div id="OpacLoginInstructions_notes" class="hint customization_note">
 Visa detta innehåll vid inloggningsrutan i OPAC när en besökare inte är inloggad. </div>

<div id="OpacMaintenanceNotice_notes" class="hint customization_note">
 Visa denna information i OPAC när systeminställningen OpacMaintenance är aktiverad. </div>

<div id="OpacMainUserBlock_notes" class="hint customization_note">
 Visa det här innehållet i en egen kolumn på förstasidan i OPAC:en. </div>

<div id="OpacMoreSearches_notes" class="hint customization_note">
 Lägg till ytterligare element i navigeringslisten under sökfältet för enkel sökning. </div>

<div id="OpacMySummaryNote_notes" class="hint customization_note">
 Anteckning som visas på låntagarens sida. Anteckningen syns bara om låntagaren är inloggad. </div>

<div id="OpacNav_notes" class="hint customization_note">
 Visa detta innehåll i den vänstra kolumnen på förstasidan och på låntagarens konto i OPAC (vanligtvis navigeringslänkar). </div>

<div id="OpacNavBottom_notes" class="hint customization_note">
 Visa följande innehåll i startsidans vänsterkolumn samt på låntagarkontot i OPAC, efter OpacNav, och före eventuella länkar till detaljer för låntagarkontot. </div>

<div id="OpacNavRight_notes" class="hint customization_note">
 Visa följande innehåll i kolumnen till höger på startsidan och under inloggningsrutan. </div>

<div id="OPACResultsSidebar_notes" class="hint customization_note">
 Visa följande innehåll under facetterna i OPACens träfflista. </div>

<div id="OpacSuggestionInstructions_notes" class="hint customization_note">
 Visa detta överst i inköpsförslagsformuläret i OPAC:en. </div>

<div id="OpacSuppressionMessage_notes" class="hint customization_note">
 Visa följande meddelande på omdirigeringssidan för dolda bibliografiska poster. Beroende av systeminställningarna OpacSuppression och OpacSuppressionRedirect. </div>

<div id="PatronSelfRegistrationAdditionalInstructions_notes" class="hint customization_note">
 Visa följande innehåll på bekräftelsesidan för låntagarens självregistrering. </div>

<div id="SCOMainUserBlock_notes" class="hint customization_note">
 Visa detta innehåll på den webbaserade utlåningsskärmen. </div>

<div id="SelfCheckHelpMessage_notes" class="hint customization_note">
 Visa följande innehåll på det webbaserade självutlåningssystemets hjälpsida. </div>

<div id="SelfCheckInMainUserBlock_notes" class="hint customization_note">
 Visa detta innehåll på återlämningsskärmen. </div>

<div id="StaffAcquisitionsHome_notes" class="hint customization_note">
 Visa detta på inköpsmodulens startsida (personalklienten). </div>

<div id="StaffAuthoritiesHome_notes" class="hint customization_note">
 Visa detta under startsidan för auktoriteter (personalklienten). </div>

<div id="StaffCataloguingHome_notes" class="hint customization_note">
 Visa detta innehåll på katalogiseringssidan i personalklienten. </div>

<div id="StaffListsHome_notes" class="hint customization_note">
 Visa detta under startsidan för listor i personalklienten. </div>

<div id="StaffPatronsHome_notes" class="hint customization_note">
 Visa detta innehåll på låntagarens sida i personalklienten. </div>

<div id="StaffPOSHome_notes" class="hint customization_note">
 Visa det här innehållet på försäljningsställets förstasida i personalklienten. </div>

<div id="StaffSerialsHome_notes" class="hint customization_note">
 Visa detta under startsidan för periodika i personalklienten. </div>
