<!-- ill-batch-table-strings.inc -->
<script>
    var ill_batch_add = _("Lägg till ny sats");
    var ill_batch_update = _("Uppdatering i sats");
    var ill_batch_none = _("Ingen");
    var ill_batch_retrieving_metadata = _("Hämtar metadata");
    var ill_batch_api_fail = _("Kunde inte hämta detaljer för satsen");
    var ill_batch_statuses_api_fail = _("Kunde inte hämta de satsvisa statusarna");
    var ill_batch_api_request_fail = _("Det gick inte att skapa lokal beställning");
    var ill_batch_requests_api_fail = _("Kunde inte hämta beställningar satsvis");
    var ill_batch_unknown = _("Okänd");
    var ill_batch_doi = _("DOI");
    var ill_batch_pmid = _("PubMed-ID");
    var ill_populate_waiting = _("Hämtar...");
    var ill_populate_failed = _("Kunde inte hämta");
    var ill_button_remove = _("Ta bort");
    var ill_batch_create_api_fail = _("Kunde inte skapa den satsvisa begäran");
    var ill_batch_update_api_fail = _("Kunde inte uppdatera de satsvisa beställningarna");
    var ill_batch_item_remove = _("Är du säker på att du vill ta bort detta exemplar från satsen?");
    var ill_batch_create_cancel_button = _("Stäng");
    var ill_batch_metadata_more = _("Mer");
    var ill_batch_metadata_less = _("Mindre");
    var ill_batch_available_via = _("Tillgänglig via");
    var ill_batch_metadata = {
        'doi': _("DOI"),
        'pmid': _("PubMed-ID"),
        'issn': _("ISSN"),
        'title': _("Titel"),
        'year': _("År"),
        'issue': _("Nummer"),
        'pages': _("Sidor"),
        'publisher': _("Förlag"),
        'article_title': _("Artikeltitel"),
        'article_author': _("Artikelförfattare"),
        'volume': _("Volym")
    };
</script>
<!-- / ill-batch-table-strings.inc -->
