<!-- ill-list-table-strings.inc -->
<script>
    var ill_borrower_details = _("Visa låntagarinformation");
    var ill_manage = _("Hantera förfrågan");
    var ill_manage_select_backend_first = _("Välj först back-end");
    var ill_all_statuses = _("Alla statusar");
    var ill_all_status_aliases = _("Alla statusar");
    var ill_no_status_alias = _("Ingen statusalias");
    var ill_status_aliases = _("Status aliases");
</script>
<!-- / ill-list-table-strings.inc -->
