<!-- ill-batch-table-strings.inc -->
<script>
    var ill_batch_borrower_details = _("Visa låntagardetaljer");
    var ill_batch_edit = _("Redigera");
    var ill_batch_delete = _("Ta bort");
    var ill_batch_confirm_delete = _("Är du säker på att du vill ta bort den här satsen? Alla bifogade beställningar kommer att kopplas bort.");
    var ill_batch_delete_fail = _("Satsen kan inte raderas");
</script>
<!-- / ill-batch-table-strings.inc -->
