<!-- installer-strings.inc -->
<script>
    var MSG_LETTERS_ONLY=(_("Ange endast bokstäver."));
    var MSG_PASSWORD_MISMATCH=(_("De angivna lösenorden matchar inte"));
    var MSG_ONE_ENROLLMENTPERIOD =(_("Vänligen välj endast en inställning för medlemsperiod. Antal månader eller exakt datum."));
    var MSG_ONLY_ONE_ENROLLMENTPERIOD=(_("Välj endast en inställning för medlemsperiod."));
    var MSG_LETTERS_NUMBERS_ONLY=(_("Skriv endast bokstäver eller siffror."));
</script>
<!-- / installer-strings.inc -->
