<div id="toolbar" class="btn-toolbar">
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-plus"></i> Ny</button>
 <ul class="dropdown-menu">
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-batch.pl?op=new">Etikettsats</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-layout.pl?op=new">Layout</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-template.pl?op=new">Etikettmall</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-profile.pl?op=new">Skrivarprofil</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-range.pl">Streckkodsintervall</a></li>
 </ul>
 </div>
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-pencil" aria-hidden="true"></i> Hantera</button>
 <ul class="dropdown-menu">
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-manage.pl?label_element=batch">Etikettsatser</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-manage.pl?label_element=layout">Layouter</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-manage.pl?label_element=template">Etikettmallar</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-manage.pl?label_element=profile">Skrivarprofiler</a></li>
 </ul>
 </div>
</div>
