<div id="toolbar" class="btn-toolbar">
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-plus"></i> Ny</button>
 <ul class="dropdown-menu">
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-batch.pl?op=new">Kortsats</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/image-manage.pl">Bild</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-layout.pl?op=new">Layout</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-template.pl?op=new">Kortmall</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-profile.pl?op=new">Skrivarprofil</a></li>
 </ul>
 </div>
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-pencil" aria-hidden="true"></i> Hantera</button>
 <ul class="dropdown-menu">
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=batch">Kortsatser</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/image-manage.pl">Bilder</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=layout">Layouter</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=template">Kortmallar</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=profile">Skrivarprofiler</a></li>
 </ul>
 </div>
</div>
