<!-- Begin Preservation Resident Search Box -->

<div id="header_search">
 <div id="preservation_search" class="residentsearch">
 <form name="find_stuff" action="/cgi-bin/koha/preservation/home.pl" method="get">
 <span class="form-title">
 <label class="control-label">Bokvård sökning</label>
 </span>

 <span class="form-content">
 <input class="head-searchbox form-control" id="preservation_search_input" name="supplier" placeholder="Bokvård sökning" type="text" />
 </span>
 <button type="submit"><i class="fa fa-arrow-right"></i></button>
 </form>
 </div>

 <ul>
 <li><a href="#preservation_search" title="Bokvård sökning"><i class="fa fa-upload"></i> <span class="tab-title">Bokvård sökning</span></a></li>
 </ul>
</div><!-- /header_search -->

<!-- End Main page Resident Search Box -->
