<div class="modal" id="overdrive-checkout" tabindex="-1" aria-labelledby="overdrive-checkoutLabel" aria-hidden="true">
 <div class="modal-dialog">
 <div class="modal-content">
 <div class="modal-header">
 <h1 class="modal-title" id="overdrive-checkoutLabel">Välj ett nedladdningsformat</h1>
 <button aria-label="Stäng" class="btn-close" data-bs-dismiss="modal" type="button"></button>
 </div>
 <form action="#" method="get" id="overdrive-checkout-form">
 <div class="modal-body">
 <input type="hidden" name="id" value="" />
 <div id="overdrive-format-list">
 </div>
 </div>
 <div class="modal-footer">
 <button type="submit" class="btn btn-primary overdrive-checkout-submit">Spara ändringar</button>
 <button type="button" class="btn btn-default" data-bs-dismiss="modal">Avbryt</button>
 </div>
 </form> <!-- /#overdrive-checkout-form -->
 </div> <!-- /.modal-content -->
 </div> <!-- /.modal-dialog -->
</div> <!-- /.modal -->
