<fieldset>
 <legend>Kodade fält</legend>
 <p>
 <label>Målgrupp</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Alla</option>
 <option value="aud:a">ungdom, generell</option>
 <option value="aud:b">förskoleålder (0-5)</option>
 <option value="aud:c">lågstadieålder (5-8)</option>
 <option value="aud:d">barn (9-14)</option>
 <option value="aud:e">ung vuxen</option>
 <option value="aud:k">vuxen, facklitteratur</option>
 <option value="aud:m">vuxen, allmän</option>
 <option value="aud:u">okänd</option>
 </select>
 </p>
 <p>
 <label>Fysisk presentation </label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Alla</option>
 <option value="Material-type:r">vanligt tryck</option>
 <option value="Material-type:d">storstil</option>
 <option value="Material-type:e">tidningsformat</option>
 <option value="Material-type:f">Braille- eller Moon-tecken</option>
 <option value="Material-type:g">mikrotryck</option>
 <option value="Material-type:h">handskrift</option>
 <option value="Material-type:i">multimedia</option>
 <option value="Material-type:j">mini-tryck</option>
 <option value="Material-type:s">elektronisk resurs </option>
 <option value="Material-type:t">mikroform</option>
 <option value="Material-type:z">annan form av textmaterial</option>
 </select>
 </p>
 <p>
 <label>Litterär genre</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Alla</option>
 <option value="Literature-Code:a">skönlitteratur</option>
 <option value="Literature-Code:b">drama</option>
 <option value="Literature-Code:c">essäer</option>
 <option value="Literature-Code:d">humor, satir</option>
 <option value="Literature-Code:e">brev</option>
 <option value="Literature-Code:f">noveller</option>
 <option value="Literature-Code:g">poesi</option>
 <option value="Literature-Code:h">tal, retorik</option>
 <option value="Literature-Code:i">libretto</option>
 <option value="Literature-Code:y">inte en litterär text</option>
 <option value="Literature-Code:z">flera/andra litterära former</option>
 </select>
 </p>
 <p>
 <label>Biografi</label>
 <select name="limit" class="subtype">
 <option value="">Alla</option>
 <option value="Biography-code:y">inte en biografi</option>
 <option value="Biography-code:a">självbiografi</option>
 <option value="Biography-code:b">individuell biografi</option>
 <option value="Biography-code:c">kollektivbiografi</option>
 <option value="Biography-code:d">innehåller biografiska data</option>
 </select>
 </p>
 <p>
 <label>Illustration </label>
 <select name="limit" class="subtype">
 <option value="">Alla</option>
 <option value="Illustration-Code:a">illustrationer</option>
 <option value="Illustration-Code:b">kartor</option>
 <option value="Illustration-Code:c">porträtt</option>
 <option value="Illustration-Code:d">charts</option>
 <option value="Illustration-Code:e">plans</option>
 <option value="Illustration-Code:f">plates</option>
 <option value="Illustration-Code:g">musik</option>
 <option value="Illustration-Code:h">faksimiler</option>
 <option value="Illustration-Code:i">heraldiska vapen</option>
 <option value="Illustration-Code:j">genealogitabeller</option>
 <option value="Illustration-Code:k">forms</option>
 <option value="Illustration-Code:l">samples</option>
 <option value="Illustration-Code:m">ljudinspelningar</option>
 <option value="Illustration-Code:n">transparencies</option>
 <option value="Illustration-Code:o">illuminations</option>
 <option value="Illustration-Code:y">inga illustrationer</option>
 </select>
 </p>
 <p>
 <label>Innehåll</label>
 <select name="limit" class="subtype">
 <option value="" >Alla</option>
 <option value="ctype:a" >bibliografi </option>
 <option value="ctype:b" >katalog</option>
 <option value="ctype:c" >register</option>
 <option value="ctype:d" >sammanfattning</option>
 <option value="ctype:e" >ordbok</option>
 <option value="ctype:f" >encyclopaedia</option>
 <option value="ctype:g" >directory</option>
 <option value="ctype:h" >projektbeskrivning</option>
 <option value="ctype:i" >statistik</option>
 <option value="ctype:j" >programmed text books</option>
 <option value="ctype:k" >patent </option>
 <option value="ctype:l" >standard </option>
 <option value="ctype:m" >dissertation or thesis</option>
 <option value="ctype:n" >laws and legislation</option>
 <option value="ctype:o" >numerisk tabell</option>
 <option value="ctype:p" >teknisk rapport</option>
 <option value="ctype:q" >examination paper</option>
 <option value="ctype:r" >literature surveys/reviews</option>
 <option value="ctype:s" >fördrag</option>
 <option value="ctype:t" >cartoons or comic strips</option>
 <option value="ctype:v" >dissertation or thesis (revised)</option>
 <option value="ctype:w" >religiös text</option>
 <option value="ctype:z" >other</option>
 </select>
 </p>
 <p>
 <label>Videotyper</label>
 <select name="limit" class="subtype">
 <option value="">Alla</option>
 <option value="Video-mt:a">film</option>
 <option value="Video-mt:b">visual projection</option>
 <option value="Video-mt:c">videoinspelning</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>Periodika</legend><p>
 <p>
 <label>Serietyp</label>
 <select name="limit" class="subtype">
 <option value="">Alla typer</option>
 <option value="Type-Of-Serial:a">Periodika</option>
 <option value="Type-Of-Serial:b">Monografiserie </option>
 <option value="Type-Of-Serial:c">Tidning</option>
 <option value="Type-Of-Serial:e">Uppdaterar lösblad </option>
 <option value="Type-Of-Serial:f">Databas</option>
 <option value="Type-Of-Serial:g">Uppdaterar webbplats </option>
 <option value="Type-Of-Serial:z">Annat</option>
 </select>
 </p>
 <p>
 <label>Periodicitet</label>
 <select name="limit" class="subtype">
 <option value="">Alla</option>
 <option value="Frequency-code:a">Dagligen</option>
 <option value="Frequency-code:b">Två gånger i veckan </option>
 <option value="Frequency-code:c">Veckovis </option>
 <option value="Frequency-code:d">Varannan vecka </option>
 <option value="Frequency-code:e">Två gånger i månaden </option>
 <option value="Frequency-code:f">Månadsvis </option>
 <option value="Frequency-code:g">Varannan månad </option>
 <option value="Frequency-code:h">Kvartalsvis </option>
 <option value="Frequency-code:i">Tre gånger om året </option>
 <option value="Frequency-code:j">Två gånger om året </option>
 <option value="Frequency-code:k">Årlig </option>
 <option value="Frequency-code:l">Biennial</option>
 <option value="Frequency-code:m">Triennial</option>
 <option value="Frequency-code:n">Tre gånger i veckan </option>
 <option value="Frequency-code:o">Tre gånger i månaden </option>
 <option value="Frequency-code:y">Utan periodicitet </option>
 <option value="Frequency-code:u">Okänd</option>
 <option value="Frequency-code:z">Annat</option>
 </select>
 </p>
 <p>
 <label>Regelbundenhet </label>
 <select name="limit" class="subtype">
 <option value="">All periodicitet</option>
 <option value="Regularity-code:a">regular</option>
 <option value="Regularity-code:b">normalised irregular</option>
 <option value="Regularity-code:y">oregelbunden</option>
 <option value="Regularity-code:u">okänd</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>Bild </legend>
 <select name="limit" class="subtype">
 <option value="">Alla</option>
 <option value="Graphics-type:a">kollage</option>
 <option value="Graphics-type:b">drawing</option>
 <option value="Graphics-type:c">painting</option>
 <option value="Graphics-type:d">photomechanical reproduction</option>
 <option value="Graphics-type:e">fotonegativ</option>
 <option value="Graphics-type:f">photoprint</option>
 <option value="Graphics-type:h">bild</option>
 <option value="Graphics-type:i">print</option>
 <option value="Graphics-type:k">technical drawing</option>
 <option value="Graphics-type:z">other non-projected graphic type</option>
 </select>
 <select name="limit" class="subtype">
 <option value="">Alla</option>
 <option value="Graphics-support:a">canvas</option>
 <option value="Graphics-support:b">bristol board</option>
 <option value="Graphics-support:c">cardboard/illustration board</option>
 <option value="Graphics-support:d">glas</option>
 <option value="Graphics-support:j">plaster</option>
 <option value="Graphics-support:k">hardboard</option>
 <option value="Graphics-support:l">porslin</option>
 <option value="Graphics-support:m">stone</option>
 <option value="Graphics-support:n">wood</option>
 <option value="Graphics-support:v">mixed collection</option>
 <option value="Graphics-support:e">synthetics</option>
 <option value="Graphics-support:f">skin</option>
 <option value="Graphics-support:g">textile</option>
 <option value="Graphics-support:h">metall</option>
 <option value="Graphics-support:i">paper</option>
 <option value="Graphics-support:z">others</option>
 <option value="Graphics-support:u">okänd</option>
 </select>
</fieldset>
