<div id="ArticleRequestsDisclaimerText_notes" class="hint customization_note">
 Tämä sisältö näytetään verkkokirjaston käyttäjälle, ennen kuin hän voi tehdä artikkelitilauksen. </div>

<div id="CatalogConcernHelp_notes"  class="hint customization_note">
 Sisällytä tämä sisältö lomakkeeseen, joka näytetään verkkokirjastossa, kun käyttäjä täyttää luettelointiongelmaraportin. </div>

<div id="CatalogConcernTemplate_notes"  class="hint customization_note">
 Esitäytä verkkokirjaston luettelointiogelmalomake tällä sisällöllä käyttäjää varten. </div>

<div id="CookieConsentBar_notes"  class="hint customization_note">
 Lisää tämä sisältö evästeidenhyväksymissivun alapalkkiin, joka näytetään OPACissa, kun CookieConsent-asetus on päällä. </div>

<div id="CookieConsentPopup_notes"  class="hint customization_note">
 Lisää tämä sisältö ponnahdusviestiin, joka näytetään verkkokirjastossa CookieConsent-asetuksen ollessa päällä ja käyttäjän klikatessa "Evästeesi"-linkkiä sivun yläpalkissa. </div>

<div id="ILLModuleCopyrightClearance_notes" class="hint customization_note">
 Sisällön lisääminen tähän osioon sallii tekijänoikeuksien lupajärjestelyt pyynnön yhteydessä. Sisältö tulee näkyviin verkkokirjastoon kaukolainapyyntöprosessin aikana. </div>

<div id="IntranetmainUserblock_notes" class="hint customization_note">
 Näytä tämä sisältö omana palstanaan virkailijaliittymän etusivulla. </div>

<div id="opaccredits_notes" class="hint customization_note">
 Lisää tämä sisältö verkkokirjaston kaikkien sivujen alapalkkiin. </div>

<div id="OpacCustomSearch_notes" class="hint customization_note">
 Korvaa verkkokirjaston sivujen yläosassa näkyvä hakulaatikko tällä sisällöllä. </div>

<div id="opacheader_notes" class="hint customization_note">
 Lisää tämä sisältö verkkokirjaston kaikkien sivujen yläpalkkiin. </div>

<div id="OpacLibraryInfo_notes" class="hint customization_note">
 Lisää tämä sisältö kirjaston tietosivulle verkkokirjastossa. </div>

<div id="OpacLoginInstructions_notes" class="hint customization_note">
 Näytä tämä sisältö verkkokirjaston kirjautumisikkunassa, kun asiakas ei ole kirjautuneena. </div>

<div id="OpacMaintenanceNotice_notes" class="hint customization_note">
 Näytä tämä sisältö verkkokirjastossa OpacMaintenance-asetuksen ollessa päällä. </div>

<div id="OpacMainUserBlock_notes" class="hint customization_note">
 Näytä tämä sisältö omana palstanaan verkkokirjaston etusivulla. </div>

<div id="OpacMoreSearches_notes" class="hint customization_note">
 Lisää navigointipalkkiin lisäelementtejä perushaun alapuolelle. </div>

<div id="OpacMySummaryNote_notes" class="hint customization_note">
 Huomautus, joka näytetään asiakkaan yhteenvetosivulla. Huomautus näkyy ainoastaan asiakkaan ollessa kirjautuneena. </div>

<div id="OpacNav_notes" class="hint customization_note">
 Näytä tämä sisältö verkkokirjaston etusivun ja asiakassivun vasemmassa palstassa (yleensä navigointilinkkejä). </div>

<div id="OpacNavBottom_notes" class="hint customization_note">
 Näytä tämä sisältö verkkokirjaston etusivun ja asiakassivun vasemmassa palstassa OpacNav-osion jälkeen, ja ennen asiakassivun linkkejä jos saatavilla. </div>

<div id="OpacNavRight_notes" class="hint customization_note">
 Näytä tämä sisältö etusivun oikeanpuoleisessa palstassa kirjautumisosion alapuolella. </div>

<div id="OPACResultsSidebar_notes" class="hint customization_note">
 Näytä tämä sisältö fasettien alla verkkokirjaston hakutuloksissa. </div>

<div id="OpacSuggestionInstructions_notes" class="hint customization_note">
 Näytä tämä sisältö hankintaehdotuslomakkeen yläosassa verkkokirjastossa. </div>

<div id="OpacSuppressionMessage_notes" class="hint customization_note">
 Näytä tämä viesti uudelleenohjaussivulla piilotetuille nimeketietueille. Asiaan liittyvät asetukset: OpacSuppression ja OpacSuppressionRedirect. </div>

<div id="PatronSelfRegistrationAdditionalInstructions_notes" class="hint customization_note">
 Näytä tämä sisältö asiakkaan itserekisteröitymisen vahvistussivulla. </div>

<div id="SCOMainUserBlock_notes" class="hint customization_note">
 Näytä tämä sisältö verkkopohjaisen omatoimilainauksen näytöllä. </div>

<div id="SelfCheckHelpMessage_notes" class="hint customization_note">
 Näytä tämä sisältö verkkopohjaisen omatoimilainauksen Ohje-sivulla. </div>

<div id="SelfCheckInMainUserBlock_notes" class="hint customization_note">
 Näytä tämä sisältö omatoimipalautuksen näytöllä. </div>

<div id="StaffAcquisitionsHome_notes" class="hint customization_note">
 Näytä tämä sisältö Hankinnat-sivulla virkailijaliittymässä. </div>

<div id="StaffAuthoritiesHome_notes" class="hint customization_note">
 Näytä tämä sisältö Auktoriteetit-sivulla virkailijaliittymässä. </div>

<div id="StaffCataloguingHome_notes" class="hint customization_note">
 Näytä tämä sisältö Kuvailu-sivulla virkailijaliittymässä. </div>

<div id="StaffListsHome_notes" class="hint customization_note">
 Näytä tämä sisältö Listat-sivulla virkailijaliittymässä. </div>

<div id="StaffPatronsHome_notes" class="hint customization_note">
 Näytä tämä sisältö Asiakkaat-sivulla virkailijaliittymässä. </div>

<div id="StaffPOSHome_notes" class="hint customization_note">
 Näytä tämä sisältö myyntipisteen aloitussivulla virkailijaliittymässä. </div>

<div id="StaffSerialsHome_notes" class="hint customization_note">
 Näytä tämä sisältö Kausijulkaisut-sivulla virkailijaliittymässä. </div>
