<!-- ill-batch-table-strings.inc -->
<script>
    var ill_batch_borrower_details = _("Tarkastele asiakkaan tietoja");
    var ill_batch_edit = _("Muokkaa");
    var ill_batch_delete = _("Poista");
    var ill_batch_confirm_delete = _("Haluatko varmasti poistaa tämän erän ? Kaikki liitetyt pyynnöt irroitetaan.");
    var ill_batch_delete_fail = _("Erän poisto epäonnistui");
</script>
<!-- / ill-batch-table-strings.inc -->
