<!-- ill-list-table-strings.inc -->
<script>
    var ill_borrower_details = _("Tarkastele asiakkaan tietoja");
    var ill_manage = _("Hallinnoi pyyntöjä");
    var ill_manage_select_backend_first = _("Valitse ensin kaukolainayhteys");
    var ill_all_statuses = _("Kaikki tilat");
    var ill_all_status_aliases = _("Kaikki tila-aliakset");
    var ill_no_status_alias = _("Ei tila-aliaksia");
    var ill_status_aliases = _("Tila-aliakset");
</script>
<!-- / ill-list-table-strings.inc -->
