<!-- ill-batch-table-strings.inc -->
<script>
    var ill_batch_add = _("Lisää uusi erä");
    var ill_batch_update = _("Päivitä erä");
    var ill_batch_none = _("Ei mitään");
    var ill_batch_retrieving_metadata = _("Haetaan tietoja");
    var ill_batch_api_fail = _("Erän tietoja ei voitu hakea");
    var ill_batch_statuses_api_fail = _("Erän tiloja ei voitu hakea");
    var ill_batch_api_request_fail = _("Paikallista pyyntöä ei voitu luoda");
    var ill_batch_requests_api_fail = _("Eräpyyntöjä ei voitu hakea");
    var ill_batch_unknown = _("Tuntematon");
    var ill_batch_doi = _("DOI");
    var ill_batch_pmid = _("PubMed ID");
    var ill_populate_waiting = _("Haetaan...");
    var ill_populate_failed = _("Haku epäonnistui");
    var ill_button_remove = _("Poista");
    var ill_batch_create_api_fail = _("Eräpyyntöä ei voitu luoda");
    var ill_batch_update_api_fail = _("Eräpyyntöä ei voitu päivittää");
    var ill_batch_item_remove = _("Haluatko varmasti poistaa tämän niteen erästä?");
    var ill_batch_create_cancel_button = _("Sulje");
    var ill_batch_metadata_more = _("Lisätietoja");
    var ill_batch_metadata_less = _("Vähemmän");
    var ill_batch_available_via = _("Saatavana");
    var ill_batch_metadata = {
        'doi': _("DOI"),
        'pmid': _("PubMed ID"),
        'issn': _("ISSN"),
        'title': _("Nimeke"),
        'year': _("Vuosi"),
        'issue': _("Numero"),
        'pages': _("Sivut"),
        'publisher': _("Julkaisija"),
        'article_title': _("Artikkelin nimeke"),
        'article_author': _("Artikkelin tekijä"),
        'volume': _("Osa")
    };
</script>
<!-- / ill-batch-table-strings.inc -->
