<!-- installer-strings.inc -->
<script>
    var MSG_LETTERS_ONLY=(_("Vain kirjaimia."));
    var MSG_PASSWORD_MISMATCH=(_("Syötetyt salasanat eivät täsmää"));
    var MSG_ONE_ENROLLMENTPERIOD =(_("Valitse voimassaoloaika kuukausissa tai päivämäärän mukaan."));
    var MSG_ONLY_ONE_ENROLLMENTPERIOD=(_("Valitse vain yksi ilmoittautumisjakso."));
    var MSG_LETTERS_NUMBERS_ONLY=(_("Vain kirjaimia ja numeroita."));
</script>
<!-- / installer-strings.inc -->
