<div id="toolbar" class="btn-toolbar">
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-plus"></i> Uusi</button>
 <ul class="dropdown-menu">
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-batch.pl?op=new">Tarrojen eräajo</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-layout.pl?op=new">Asettelu</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-template.pl?op=new">Tarrapohja</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-profile.pl?op=new">Tulostinprofiili</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-range.pl">Viivakoodiväli</a></li>
 </ul>
 </div>
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-pencil" aria-hidden="true"></i> Käsittelijä</button>
 <ul class="dropdown-menu">
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-manage.pl?label_element=batch">Tarraerät</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-manage.pl?label_element=layout">Asettelut</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-manage.pl?label_element=template">Tarrapohjat</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-manage.pl?label_element=profile">Tulostinprofiilit</a></li>
 </ul>
 </div>
</div>
