<div id="toolbar" class="btn-toolbar">
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-plus"></i> Uusi</button>
 <ul class="dropdown-menu">
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-batch.pl?op=new">Kirjastokorttierä</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/image-manage.pl">Kuva</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-layout.pl?op=new">Asettelu</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-template.pl?op=new">Kortin luontipohja</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-profile.pl?op=new">Tulostinprofiili</a></li>
 </ul>
 </div>
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-pencil" aria-hidden="true"></i> Käsittely</button>
 <ul class="dropdown-menu">
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=batch">Kirjastokorttierät</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/image-manage.pl">Kuvat</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=layout">Asettelut</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=template">Kortin luontipohjat</a></li>
 <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=profile">Tulostinprofiilit</a></li>
 </ul>
 </div>
</div>
