<fieldset>
 <legend>Koodikentät</legend>
 <p>
 <label>Kohderyhmä</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Kaikki</option>
 <option value="aud:a">lapset ja nuoret, yleinen</option>
 <option value="aud:b">pre-primary (0-5)</option>
 <option value="aud:c">ala-asteikäiset</option>
 <option value="aud:d">lapset (9-14)</option>
 <option value="aud:e">nuoret aikuiset</option>
 <option value="aud:k">aikuiset, vakava</option>
 <option value="aud:m">aikuiset, Yleinen</option>
 <option value="aud:u">tuntematon</option>
 </select>
 </p>
 <p>
 <label>Fyysinen kuvailu:</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Kaikki</option>
 <option value="Material-type:r">tavanomainen painotuote</option>
 <option value="Material-type:d">isoteksti</option>
 <option value="Material-type:e">newspaper format</option>
 <option value="Material-type:f">Moonin tai Braillen kirjoitus</option>
 <option value="Material-type:g">microprint</option>
 <option value="Material-type:h">käsin kirjoitettu</option>
 <option value="Material-type:i">multimedia</option>
 <option value="Material-type:j">mini-print</option>
 <option value="Material-type:s">electronic ressource</option>
 <option value="Material-type:t">microform</option>
 <option value="Material-type:z">other form of textual material</option>
 </select>
 </p>
 <p>
 <label>Kirjallisuuden genre</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Kaikki</option>
 <option value="Literature-Code:a">kaunokirjallisuus</option>
 <option value="Literature-Code:b">draama</option>
 <option value="Literature-Code:c">esseet</option>
 <option value="Literature-Code:d">huumori, satiiri</option>
 <option value="Literature-Code:e">kirjeet</option>
 <option value="Literature-Code:f">novellit</option>
 <option value="Literature-Code:g">runo</option>
 <option value="Literature-Code:h">luennot, puheet</option>
 <option value="Literature-Code:i">libretto</option>
 <option value="Literature-Code:y">Ei tekstiä</option>
 <option value="Literature-Code:z">multiple/other literary forms</option>
 </select>
 </p>
 <p>
 <label>Elämäkerta</label>
 <select name="limit" class="subtype">
 <option value="">Kaikki</option>
 <option value="Biography-code:y">not a biography</option>
 <option value="Biography-code:a">Omaelämäkerta</option>
 <option value="Biography-code:b">elämäkerta</option>
 <option value="Biography-code:c">kokoomaelämäkerta</option>
 <option value="Biography-code:d">Sisältää elämäkertatietoja</option>
 </select>
 </p>
 <p>
 <label>Kuvitus</label>
 <select name="limit" class="subtype">
 <option value="">Kaikki</option>
 <option value="Illustration-Code:a">kuvitettu</option>
 <option value="Illustration-Code:b">kartat</option>
 <option value="Illustration-Code:c">portraits</option>
 <option value="Illustration-Code:d">kaaviot</option>
 <option value="Illustration-Code:e">plans</option>
 <option value="Illustration-Code:f">plates</option>
 <option value="Illustration-Code:g">musiikki</option>
 <option value="Illustration-Code:h">Näköispainos</option>
 <option value="Illustration-Code:i">vaakuna</option>
 <option value="Illustration-Code:j">Sukutaulut</option>
 <option value="Illustration-Code:k">muodostaa</option>
 <option value="Illustration-Code:l">näytteet</option>
 <option value="Illustration-Code:m">äänitteet</option>
 <option value="Illustration-Code:n">kalvot</option>
 <option value="Illustration-Code:o">kuvitus</option>
 <option value="Illustration-Code:y">no illustrations</option>
 </select>
 </p>
 <p>
 <label>Sisältö</label>
 <select name="limit" class="subtype">
 <option value="" >Kaikki</option>
 <option value="ctype:a" >bibliografia</option>
 <option value="ctype:b" >kokoelma</option>
 <option value="ctype:c" >hakemisto</option>
 <option value="ctype:d" >tiivistelmä</option>
 <option value="ctype:e" >sanakirja, sanasto</option>
 <option value="ctype:f" >tietosanakirja</option>
 <option value="ctype:g" >hakemisto</option>
 <option value="ctype:h" >Volyymin kuvaus:</option>
 <option value="ctype:i" >tilastot</option>
 <option value="ctype:j" >programmed text books</option>
 <option value="ctype:k" >patentti</option>
 <option value="ctype:l" >standard</option>
 <option value="ctype:m" >väitöskirja tai opinnäytetyö</option>
 <option value="ctype:n" >laws and legislation</option>
 <option value="ctype:o" >numeric table</option>
 <option value="ctype:p" >tekninen raportti</option>
 <option value="ctype:q" >Tutkintotodistus</option>
 <option value="ctype:r" >kirjallisuuskatsaukset, arvostelut</option>
 <option value="ctype:s" >sopimukset</option>
 <option value="ctype:t" >sarjakuvat</option>
 <option value="ctype:v" >väitöskirja tai opinnäytetyö (tarkistettu)</option>
 <option value="ctype:w" >uskonnollinen teksti</option>
 <option value="ctype:z" >muu</option>
 </select>
 </p>
 <p>
 <label>Videolajit</label>
 <select name="limit" class="subtype">
 <option value="">Kaikki</option>
 <option value="Video-mt:a">elokuva</option>
 <option value="Video-mt:b">projektio</option>
 <option value="Video-mt:c">Videotallenne</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>Kausijulkaisut</legend><p>
 <p>
 <label>Kausijulkaisulaji</label>
 <select name="limit" class="subtype">
 <option value="">Kaikki</option>
 <option value="Type-Of-Serial:a">Aikakauslehti</option>
 <option value="Type-Of-Serial:b">Monografiasarja</option>
 <option value="Type-Of-Serial:c">Sanomalehti</option>
 <option value="Type-Of-Serial:e">Päivittyvä irtolehtijulkaisu</option>
 <option value="Type-Of-Serial:f">Tietokanta</option>
 <option value="Type-Of-Serial:g">Päivittyvä verkkosivusto</option>
 <option value="Type-Of-Serial:z">Muu</option>
 </select>
 </p>
 <p>
 <label>Ilmestymistiheys</label>
 <select name="limit" class="subtype">
 <option value="">Kaikki</option>
 <option value="Frequency-code:a">Päivittäin</option>
 <option value="Frequency-code:b">Kaksi kertaa viikossa</option>
 <option value="Frequency-code:c">Kerran viikossa</option>
 <option value="Frequency-code:d">Kerran kahdessa viikossa</option>
 <option value="Frequency-code:e">Kaksi kertaa kuukaudessa</option>
 <option value="Frequency-code:f">Kerran kuukaudessa</option>
 <option value="Frequency-code:g">Joka toinen kuukausi</option>
 <option value="Frequency-code:h">Neljäsosavuosittain</option>
 <option value="Frequency-code:i">Kolme kertaa vuodessa</option>
 <option value="Frequency-code:j">Puolivuosittain</option>
 <option value="Frequency-code:k">Kerran vuodessa</option>
 <option value="Frequency-code:l">Kerran kahdessa vuodessa</option>
 <option value="Frequency-code:m">Kerran kolmessa vuodessa</option>
 <option value="Frequency-code:n">Kolme kertaa viikossa</option>
 <option value="Frequency-code:o">Kolme kertaa kuukaudessa</option>
 <option value="Frequency-code:y">Epäsäännöllinen</option>
 <option value="Frequency-code:u">Tuntematon</option>
 <option value="Frequency-code:z">Muu</option>
 </select>
 </p>
 <p>
 <label>Säännöllisyys</label>
 <select name="limit" class="subtype">
 <option value="">Mikä tahansa säännöllisyys</option>
 <option value="Regularity-code:a">regular</option>
 <option value="Regularity-code:b">normalised irregular</option>
 <option value="Regularity-code:y">Epäsäännöllinen</option>
 <option value="Regularity-code:u">tuntematon</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>Kuva</legend>
 <select name="limit" class="subtype">
 <option value="">Kaikki</option>
 <option value="Graphics-type:a">kollaasi</option>
 <option value="Graphics-type:b">piirustus</option>
 <option value="Graphics-type:c">maalaus</option>
 <option value="Graphics-type:d">fotomekaaninen jäljennös</option>
 <option value="Graphics-type:e">valokuvanegatiivi</option>
 <option value="Graphics-type:f">valokuvatuloste</option>
 <option value="Graphics-type:h">kuva</option>
 <option value="Graphics-type:i">painotuote</option>
 <option value="Graphics-type:k">tekninen piirustus</option>
 <option value="Graphics-type:z">other non-projected graphic type</option>
 </select>
 <select name="limit" class="subtype">
 <option value="">Kaikki</option>
 <option value="Graphics-support:a">maalauskangas</option>
 <option value="Graphics-support:b">Bristol-taulu</option>
 <option value="Graphics-support:c">kortti/kuvataulu</option>
 <option value="Graphics-support:d">lasi</option>
 <option value="Graphics-support:j">Kipsi</option>
 <option value="Graphics-support:k">kovalevy</option>
 <option value="Graphics-support:l">porcelaine</option>
 <option value="Graphics-support:m">kivi</option>
 <option value="Graphics-support:n">puu</option>
 <option value="Graphics-support:v">kokoelma</option>
 <option value="Graphics-support:e">Synteettinen</option>
 <option value="Graphics-support:f">in</option>
 <option value="Graphics-support:g">Tekstiili</option>
 <option value="Graphics-support:h">metal</option>
 <option value="Graphics-support:i">paper</option>
 <option value="Graphics-support:z">muut</option>
 <option value="Graphics-support:u">tuntematon</option>
 </select>
</fieldset>
