<div id="mana_comment_progress" class="alert alert-info mana_comment_status" style="display:none">
 <div id="loading"> <img src="[% interface | html %]/[% theme | html %]/img/spinner-small.gif" alt="" /> Skicka in kommentar </div>
</div>
<div id="mana_comment_success" class="alert alert-info mana_comment_status" style="display:none">
 Din kommentar har skickats in </div>
<div id="mana_comment_failed" class="alert alert-warning mana_comment_status" style="display:none">
 Din kommentar kunde inte skickas in. Försök igen lite senare. </div>
